### ISSUE TITLE
[Question] Code coverage ?

### ISSUE THREAD

**Issue by MathieuNls** [michaelbromley/ng2-pagination#100]
Hi Michael,

Thanks a lot for your library. 

I am using it daily and I am about to create my own lib using yours as guidelines / model.

The only thing that I'd love to add is code coverage. Did you try ? If not, where would you begin?

If I manage to get it work, I will open a proper issue and PR so you can see if you want it too.

M.

**Comment by michaelbromley** [comment]
Hi,

Great idea and no, I've not tried it yet. I guess I would begin here: https://karma-runner.github.io/0.8/config/coverage.html - seems like it would not be too difficult since we already use Karma for the tests.

And yeah, a PR would be most welcome if you get it working!
