### ISSUE TITLE
auto hide and itemsPerPage after search not working 

### ISSUE THREAD

**Issue by rahuldev761** [michaelbromley/ng2-pagination#101]
hi am using it on by table list but I have some issue on it.Please help me out.

- First is auto hide not working when I filter table list
- Second is when I search data in column and search result is more then **itemsPerPage**, It show in single page. **itemsPerPage** not working. Like as If **itemsPerPage=4** and search **result is =7** then all rows show in single page.
  

here is my code
```
 public paginationConfig: PaginationInstance = {
    id: 'advanced',
    itemsPerPage: 4,
    currentPage: 1
  };
```
**html**
`<template ngFor let-customer [ngForOf]="customers | paginate:paginationConfig>`
 ```
<pagination-controls
      [id]="paginationConfig.id"
      [autoHide]=true
      [maxSize]=7
      [directionLinks]=true
      (pageChange)="onPageChange($event)"
      #api>
    </pagination-controls>
```

**Comment by michaelbromley** [comment]
Hi,

I do not understand how you are performing searching - it is not indicated anywhere in your code. The PaginatePipe is only aware of the collection that is passed into it via the ngFor expression. To filter results you would use a pipe before the PaginatePipe which filters down the array to just the matching items. In this case it should work - see the demo: http://michaelbromley.github.io/ng2-pagination/#/advanced

**Comment by michaelbromley** [comment]
I'm closing this issue because further data was needed but was not provided. If you want to continue the thread, feel free to re-open.
