### ISSUE TITLE
Template error when saving ngfor index

### ISSUE THREAD

**Issue by lgarro** [michaelbromley/ng2-pagination#102]
**Angular 2 version**: 2.0.0
*ng2-pagination version**: ng2-pagination@0.4.1

**Description of issue**:

Getting template parse errors when trying to save the index of the ngfor with let i =index syntax.

**Steps to reproduce**:

Create a list to be paginated and displayed with pagination controls like this 
```<div *ngFor="let f of films; let i=index| paginate: { id: 'someid',itemsPerPage: 6, currentPage: pageNumber,totalItems:total}"```

**Expected result**:

Can access index variable

**Actual result**:

Template parse errors 

```

```

**Comment by michaelbromley** [comment]
The problem is that the ngFor expression is incorrect. You need to put the `let i=index` *after* the collection and pipes:

```HTML
<div *ngFor="let f of films | paginate: { id: 'someid',itemsPerPage: 6, currentPage: pageNumber,totalItems:total}; let i=index">
```

**Comment by MrMondejar** [comment]
Hello, I'm trying this solution or
` <div *ngFor="let f of films | paginate: { id: 'someid',itemsPerPage: 6, currentPage: pageNumber,totalItems:total}; #i=index">`
 and both aren't working

**Comment by MrMondejar** [comment]
@michaelbromley  forget my last comment, I had a typo, sorry
