### ISSUE TITLE
Override current li style

### ISSUE THREAD

**Issue by kenp77** [michaelbromley/ng2-pagination#104]
Hi, 

There's a way to overide the current li style and change it from blue to gray ? 
I tried this but i still have the blue color : 
```
pagination-controls li.current{
 background : gray;
}
```
Thanks

**Comment by michaelbromley** [comment]
See https://github.com/michaelbromley/ng2-pagination/issues/64

**Comment by kenp77** [comment]
Why you are closing an issue without a confirmation from the user who is reporting the issue ? Maybe it worked for someonelse but not for me :( .  It didn't work for me and i still have a blue background for the current li The ```
 pagination-controls li.current{
 background : gray;
}
```
Didn't work. When i only put pagination-controls li withtout the current class the gray is applied for all the link except for the current !

**Comment by michaelbromley** [comment]
Hi,

Sorry, I thought it was pretty much an exact duplicate and would be simple to fix. In linking to that other issue, I meant to point out the use of the `/deep/` selector, which allows you to target elements within the shadow DOM boundary created by Angular.

What happens if you use:

```css
pagination-controls /deep/ .ng2-pagination li {
  background: gray;
}
```

?

**Comment by kenp77** [comment]
Hi,

I put your code in my main scss file `main.s`css but the style is not overided and i still have the blue background in the current li. So the problem is more related to the current li.

**Comment by michaelbromley** [comment]
You are totally correct. The PaginationControlsComponent should perhaps not use the emulated shadow DOM style mode, which would make it easier to override the styles.

For now, you can force it with an `!important` marker in your css:

```css
pagination-controls /deep/ .ng2-pagination li.current {
  background: gray !important;
}
```

See a demo here: http://plnkr.co/edit/a9AofVgQPgIWu0M0FF9Y?p=preview

**Comment by kenp77** [comment]
The !important hack solved the problem. Thank you. Now you can close it :)

**Comment by markkesty** [comment]
It still doesn't work for me. All I did was add the bootstrap.css cdn after the foundation.css in the index file and then applied your fix to the template in app.ts.

Please see the following plunk:
http://plnkr.co/edit/GsEOqTenaDmi0iekGeEh?p=preview

**Comment by Farias2015** [comment]
Hi,
how do I centralize the component with override style?
