### ISSUE TITLE
More than one is not working

### ISSUE THREAD

**Issue by hassan-fl** [michaelbromley/ng2-pagination#107]
More than one list/pagination in one template is not working.

**Comment by michaelbromley** [comment]
Hi,

Please provide some more information - the more the better:

1) What have you tried so far? show some code.
2) Describe exactly what you mean by "is not working" - What happens which differs from your expectation? Any error messages?
3) If possible, provide a reproduction of the issue using [this Plunker demo](http://plnkr.co/edit/JVQMPvV8z2brCIzdG3N4?p=preview)

**Comment by hassan-fl** [comment]
Hi,
Please look at this: [Plunker demo](http://plnkr.co/edit/rFI1xE?p=preview)
I have to collection (and loop/pagination in one template), so when I click and change one list pagination, it also affect another one.

**Comment by michaelbromley** [comment]
Thanks for the demo - when you have more than one instance, you need to specify the `id` property on both the `PaginatePipe` and the `PaginationControlsComponent`:

```HTML
<div>
  <ul>
    <li *ngFor="let item of collection1 | paginate: { itemsPerPage: 10, currentPage: p1, id: 'one' }">{{ item }}</li>
  </ul>
  <pagination-controls (pageChange)="p1 = $event" #api id="one"></pagination-controls>
</div>
<div>
  <ul>
    <li *ngFor="let item of collection2 | paginate: { itemsPerPage: 10, currentPage: p2, id: 'two' }">{{ item }}</li>
  </ul>
  <pagination-controls (pageChange)="p2 = $event" #api id="two"></pagination-controls>
</div>
```

See an [updated plunker demo here](http://plnkr.co/edit/0DlE6I?p=preview)

**Comment by Pinank** [comment]
It's working fine for 2 but not working in 
<tr *ngFor="let unit of units | paginate: {id: unit.id, itemsPerPage: 8, currentPage: page, totalItems: units.length};let i=index;">
scenirio

**Comment by gmkhussain** [comment]
Maybe it's helpful try this

```
<div *ngFor="let id of [1, 2]; let i = index;">
  <ul>
    <li *ngFor="let item of collection | paginate: { itemsPerPage: 10, currentPage: p[i], id: id }">{{ item }}</li>
   </ul>
   <pagination-controls (pageChange)="p[i] = $event" [id]="id"></pagination-controls>
</div>
```

Read the detail here 
https://github.com/michaelbromley/ngx-pagination/tree/20a2db2501b842826e28031f5d0e2c894401a2b9#multiple-instances
