### ISSUE TITLE
Error after import the modules

### ISSUE THREAD

**Issue by zh355245849** [michaelbromley/ng2-pagination#108]
**Angular 2 version**: 2.1.2

**ng2-pagination version**: 1.0.1

**Description of issue**: 
```
Error: (SystemJS) Unexpected token <
	SyntaxError: Unexpected token <
	    at eval (<anonymous>)
	    at Object.eval (http://localhost:3000/app/app.module.js:15:24)
	    at eval (http://localhost:3000/app/app.module.js:64:4)
	    at eval (http://localhost:3000/app/app.module.js:65:3)
	Evaluating http://localhost:3000/ng2-pagination
	Evaluating http://localhost:3000/app/app.module.js
	Evaluating http://localhost:3000/app/main.js
	Error loading http://localhost:3000/app/main.js
	    at eval (<anonymous>)
	    at Object.eval (http://localhost:3000/app/app.module.js:15:24)
	    at eval (http://localhost:3000/app/app.module.js:64:4)
	    at eval (http://localhost:3000/app/app.module.js:65:3)
	Evaluating http://localhost:3000/ng2-pagination
	Evaluating http://localhost:3000/app/app.module.js
	Evaluating http://localhost:3000/app/main.js
	Error loading http://localhost:3000/app/main.js
```

After I import the page modules in appModule

Any relevant code:

```TypeScript
import { NgModule } from "@angular/core";
import { BrowserModule } from "@angular/platform-browser";
import { HttpModule, JsonpModule } from '@angular/http';
import { RouterModule } from '@angular/router';
import { Ng2PaginationModule } from 'ng2-pagination';

import { AppComponent } from "./components/app/app.component";
import { BookFormComponent } from "./components/book-form/book-form.component";
import { BookComponent } from "./components/book/book.component";
import { BookDetailComponent } from "./components/book-detail/book-detail.component";
import { BookListComponent } from "./components/book-list/book-list.component";

import { PostComponent } from "./components/post/post.component";
import { PostListComponent } from "./components/post-list/post-list.component";
import { PostDetailComponent } from "./components/post-detail/post-detail.component";
import { PostFormComponent } from "./components/post-form/post-form.component";

import { BookService } from "./services/books/books.service";
import { PostService } from "./services/posts/posts.service";

@NgModule({
  imports: [
    BrowserModule,
    HttpModule,
    JsonpModule,
    Ng2PaginationModule,
    RouterModule.forRoot([
      {
        path: '',
        redirectTo: 'book-list',
        pathMatch: 'full'
      },
      { path: 'book-list', component: BookListComponent },
      { path: 'book-list/new', component: BookFormComponent },
      { path: 'book-list/:id', component: BookDetailComponent },
      { path: 'post-list', component: PostListComponent },
      { path: 'post-list/:id', component: PostDetailComponent },
      { path: 'post-list/form/new', component: PostFormComponent }
    ])
  ],
  declarations: [
    BookComponent, BookListComponent, AppComponent, BookDetailComponent, BookFormComponent,
    PostComponent, PostListComponent, PostDetailComponent, PostFormComponent
  ],
  providers: [BookService, PostService],
  bootstrap: [AppComponent]
})

export class AppModule { }
```

```TypeScript
import { Component, ChangeDetectionStrategy } from "@angular/core";
import { OnInit } from "@angular/core";
import  { PaginationInstance } from "ng2-pagination";


import { IPost } from "../../interfaces/posts/ipost";
import { PostService } from "../../services/posts/posts.service";

@Component({
    selector: "post-list",
    templateUrl: "./app/components/post-list/post-list.component.html"
})
export class PostListComponent implements OnInit {

	page: number = 1;
    postList: IPost[];

    async ngOnInit() {
        this.postList = await this.postService.getAllPosts();
    }

    constructor(private postService: PostService) { 
    }
}
```

```HTML
<section>
    <h1>Some posts</h1>
    <p>There are many other story posts in the world, but here are like 20 of them</p>

    <post *ngFor="let post of postList | paginate: { itemsPerPage: 20, currentPage: page }" [post]=post ></post>
    
	<pagination-controls (pageChange)="page = $event"></pagination-controls>
</section>
```

**Comment by michaelbromley** [comment]
I'm not an expert on SystemJS, but I suspect the error may be caused by some problem with your SystemJS config. Could you paste your config?

**Comment by zh355245849** [comment]
Sure. My config is:

/**
 * System configuration for Angular samples
 * Adjust as necessary for your application needs.
 */
(function (global) {
  System.config({
    paths: {
      // paths serve as alias
      'npm:': 'public/js/node_modules/'
    },
    // map tells the System loader where to look for things
    map: {
      // our app is within the app folder
      app: 'app',

      // angular bundles
      '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
      '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
      '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
      '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
      '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
      '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
      '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
      '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
      '@angular/upgrade': 'npm:@angular/upgrade/bundles/upgrade.umd.js',

      // other libraries
      'rxjs':                      'npm:rxjs',
      'angular-in-memory-web-api': 'npm:angular-in-memory-web-api/bundles/in-memory-web-api.umd.js'
    },
    // packages tells the System loader how to load when no filename and/or no extension
    packages: {
      app: {
        main: './main.js',
        defaultExtension: 'js'
      },
      rxjs: {
        defaultExtension: 'js'
      }
    }
  });
})(this);

**Comment by michaelbromley** [comment]
Looks like you don't have any config to tell SystemJS where to find the `ng2-pagination` module. If you look at [this plunker demo](http://plnkr.co/edit/JVQMPvV8z2brCIzdG3N4?p=preview) you can see how I do the config for it, specifically:

```JavaScript
var  map = {
    'ng2-pagination':  'https://rawgit.com/michaelbromley/ng2-pagination/master/dist' 
};

  //packages tells the System loader how to load when no filename and/or no extension
var packages = {
    'ng2-pagination':             { main: 'ng2-pagination.js', defaultExtension: 'js' }
};
```

The path to the map value would be different since you'll be using a local copy, so probably something like `ng2-pagination/master/dist`.

**Comment by zh355245849** [comment]
Hi, Thank you for your answer. But I still get the same error. My ng2-pagination is in the node-modules package. I add that in map:
`map: {
      // our app is within the app folder
      app: 'app',

      // angular bundles
      '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
      '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
      '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
      '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
      '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
      '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
      '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
      '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
      '@angular/upgrade': 'npm:@angular/upgrade/bundles/upgrade.umd.js',
      'ng2-pagination':  '../../../node_modules/ng2-pagination',
      // other libraries
      'rxjs':                      'npm:rxjs',
      'angular-in-memory-web-api': 'npm:angular-in-memory-web-api/bundles/in-memory-web-api.umd.js'
    }`

and package:

`packages: {
      app: {
        main: './main.js',
        defaultExtension: 'js',
        'ng2-pagination': { main: 'ng2-pagination.js', defaultExtension: 'js' }
      },
      rxjs: {
        defaultExtension: 'js'
      }
    }`
Is that right?

**Comment by michaelbromley** [comment]
As I say, I'm no SystemJS expert, so you'd probably be better off taking this to another forum like StackOverflow. One thing that looks strange to me is that you have the path as `'../../../node_modules/ng2-pagination'` whereas all the other imports are of the form `'npm:module'`. Have you tried `'npm:ng2-pagination'`?

**Comment by EugeneCh** [comment]
You should add `'ng2-pagination': 'npm:ng2-pagination/dist/ng2-pagination-bundle.js'`

**Comment by EugeneCh** [comment]
But after this fix I got another issue `Error: (SystemJS) Unexpected value 'undefined' imported by the module 'AppModule'`

**Comment by jsunebring** [comment]
I ran into the same issue but sorted it with some help from the plunkr posted above.
Point the library to the dist-folder under npm.

`'ng2-pagination':            'npm:ng2-pagination/dist/'`

Then add a declaration under packages pointing to the main .js file as per the plunkr.


`      },
      'ng2-pagination': {
        defaultExtension: 'js',
        main: 'ng2-pagination.js'
      }`

**Comment by henioStraszny** [comment]
@jsunebring I can confirm that this fixes the issue.
