### ISSUE TITLE
(SystemJS) Unexpected value 'undefined' imported by the module 'AppModule'

### ISSUE THREAD

**Issue by BBegouin** [michaelbromley/ng2-pagination#109]
**Angular 2 version**: 2.2.4
**ng2-pagination version**: 1.0.1

**Description of issue**:

I am currently experiencing a weird behaviour, I use systemJS for loading ng2-paginationModule, 
but I've got " (SystemJS) Unexpected value 'undefined' imported by the module 'AppModule' "
Suggesting that there is a problem loading the bundle. 

Here is my app.component.ts : 

```
import {Ng2PaginationModule} from 'ng2-pagination';

import { CKEditorModule } from 'ng2-ckeditor';
import { PaginationService} from 'ng2-pagination';

@NgModule({

  imports: [HttpModule,
            BrowserModule,
            RouterModule.forRoot(routes),
            Ng2PaginationModule,
            ServicesModule.forRoot()],

  declarations: [AppComponent],

  providers: [{
    provide: APP_BASE_HREF,
    useValue: '<%= APP_BASE %>'
  },
    AuthService,
    BlogService ],

  bootstrap: [AppComponent]

})
```
Here is my system.config.js line, concerned in loading ng2-pagination

`"ng2-pagination":"node_modules/ng2-pagination/dist/ng2-pagination-bundle.js"`

**Steps to reproduce**:
Use latest version of [angular2-seed](https://github.com/mgechev/angular-seed), and try to load the ng2-pagination bundle : 
- install ng2-pagination with npm
- add module in app.module.ts
- modify tools/config/seed.config.ts to update systemjs configuration, for loading pagination bundle
- try to start the app with npm start

Do you know if there is any trouble with latest angular2 version ? 
thanks for your work. 

cheers

**Edit**

Seems to be an import error. Apparently impossible to import module definition from the barrel. 
But when the import error is tackled, another error arise : 
"The pipe 'paginate' could not be found"
Any clue ?

**Comment by michaelbromley** [comment]
Hi,

I don't use SystemJS in any of my projects, so I may not be the best to advise, but I did manage to get it working for [the plunker demo](http://plnkr.co/edit/JVQMPvV8z2brCIzdG3N4?p=preview). If you take a look at that you'll notice that I don't use the System bundle, I just point to `ng2-pagination.js` in the `dist` folder. Have you tried a config like that?

**Comment by BBegouin** [comment]
Thank you for your answer ! 
My bad. 
noob error. 
Module import error.

**Comment by henioStraszny** [comment]
Hello, I've exactly the same problem, @BBegouin could you explain what have you changed?
