### ISSUE TITLE
Does this library support dynamic Paging?

### ISSUE THREAD

**Issue by masonz** [michaelbromley/ng2-pagination#11]
i tried this library and it works good for local list, and would like to use it for some api that returns json (a list + total items count). But once I bind the "totalItems" property and when the list is updated by the returned json, the browser get frozen.

will this library work in this case?

**Comment by michaelbromley** [comment]
Hi,

I am currently doing a major refactor of this lib. I'm including a live demo of this exact scenario. Hopefully I'll have it updated in the next few days, and I'll update this issue when it is resolved.

**Comment by michaelbromley** [comment]
Please see the latest version (beta.1), as well as the updated demo and let me know if that works for you.

**Comment by buiphu** [comment]
thanks,
i had update latest version (beta.1).

it had a bug in directives: [PaginationControlsCmp]

import {PaginatePipe, PaginationControlsCmp, PaginationService} from 'ng2-pagination';
i used PaginationControlsCmp it don't run 

but i used directives: [PAGINATION_DIRECTIVES] 

how used PaginationControlsCmp . i want used PaginationControlsCmp

**Comment by buiphu** [comment]
i used custom template it ok

**Comment by masonz** [comment]
excellent! works for me, thank you.

**Comment by michaelbromley** [comment]
Great, closing.
