### ISSUE TITLE
Increase Font Size

### ISSUE THREAD

**Issue by shabbir-dhangot** [michaelbromley/ng2-pagination#112]
**Description of issue**:
I added pagination. Its working fine. I have small issue of font. Why pagination-control showing in small size. here is [screenshot](http://prnt.sc/dqj57i)
**Expected result**:
Its should be little larger. I am not able to get the problem.
**Actual result**:
here is current result [screenshot](http://prnt.sc/dqj57i)

**Comment by michaelbromley** [comment]
Hi, see issue #104 for advice on styling the default template.

Note that I also intend at some point to re-work the API of the default template to make it easier to style (tracked by #106)

**Comment by shabbir-dhangot** [comment]
Thank you. That helped

> pagination-controls /deep/ .ng2-pagination li.current {
            background-color: #273645 !important;
        }
        pagination-controls /deep/ .ng2-pagination li {
            font-size: 14px !important;
            cursor:pointer;
        }
