### ISSUE TITLE
Translation for default pagination template

### ISSUE THREAD

**Issue by kresogalic8** [michaelbromley/ng2-pagination#113]
Hey guys, I like your pagination, but is there a way to translate default pagination? 

```
<element *ngFor="let item of collection | paginate: { id: 'foo',
                                                      itemsPerPage: pageSize,
                                                      currentPage: p,
                                                      totalItems: total }">...</element>
```

**Comment by michaelbromley** [comment]
If you are referring to the "You're on page" text then no, the only thing to do is make a custom template.

Note that I plan to re-work the default template for this and other reasons: https://github.com/michaelbromley/ng2-pagination/issues/106
