### ISSUE TITLE
Prevent from setting totalItems for in memory pagination.

### ISSUE THREAD

**Issue by MateuszG** [michaelbromley/ng2-pagination#115]
**Angular 2 version**:

> 2.4.3

**ng2-pagination version**:

> 2.0.0

**Description of issue**:

> When I use in config of pipe property totalItems for example: totalItems: products.length for in-memory paging, paginate pipe stop working. You can change pages but paginate list all items on every page.

**Steps to reproduce**:

**Expected result**:

>  I think that there should be more visible warning in the documentation for developer, that totalItems shoud be removed or maybe make in memory page working with this propery, add new property (mode of pagination) for pagination config?

**Actual result**:

> There is not info at all in module, only short information in readme. I spent a few hours figuring out what is the reason.

Any relevant code:
```

 *ngFor="let product of products | paginate: { id: 'cart', itemsPerPage: itemsPerPage, currentPage: currentPage, totalItems: products.length}; let i = index">

```

**Comment by michaelbromley** [comment]
Hi,

Thanks for the feedback, and I'm sorry you lost a few hours trying to figure this out!

I agree that it would be better to have the in-memory mode just work even if you specify `totalItems: collection.length`. I will look at adding this into the next release.
