### ISSUE TITLE
pagination-controls id="" causin issue.

### ISSUE THREAD

**Issue by Locheed** [michaelbromley/ng2-pagination#116]
=======

**Angular 2 version**: 2.3.1

**ng2-pagination version**: 2.0.0

**Description of issue**:
Spend a whole day figuring out why my pagination control doesn't work. It didn't show page numbering or a previous button. Only next button was there and it also did nothing.

Finally, I removed id="" from my pagination-controller and it works.

**Steps to reproduce**:
Use id="" like it's used in docs. Also tested this with your example plunker and it bugs there too.

**Expected result**:
Working pagination with an id.

**Actual result**:
Only next-button visible.

Any relevant code:
```
<pagination-controls  id="some_id"
                      (pageChange)="pageChanged($event)"
                      maxSize="9"
                      directionLinks="true"
                      autoHide="true"
                      previousLabel="Previous"
                      nextLabel="Next">
</pagination-controls>
```

**Comment by michaelbromley** [comment]
Hi,

Did you try to set an id on the pagination controls without setting the corresponding id on the "paginate" pipe? If so, the docs do state the following:

> **id** [string] If you need to support more than one instance of pagination at a time, set the id and ensure it matches the id attribute of the PaginationControlsComponent / PaginationControlsDirective (see below).

and 

> **id** [string] If you need to support more than one instance of pagination at a time, set the id and ensure it matches the id set in the PaginatePipe config.

So I do not think that a working pagination should necessarily be the *expected* result based on the above.

However, I fully agree that there should be some indication of what exactly is going wrong, along the lines of a console warning ("The PaginationControlsComponent has been assigned the id 'some_id' without a corresponding id being used with the PaginatePipe" or some such).

I'll add this to the next release.

**Comment by Locheed** [comment]
That could be a good thing to add.

But for me, I made sure several times that I have a **id: string** on my pipe and **id="string"** on my control. I also tested this on your plunker and it didn't work there either.

**Comment by michaelbromley** [comment]
If in the pipe you do `id: some_id`, then it will assume there is a component variable named "some_id". If none is defined, the id will be `undefined` (I guess).

If it is just a string, then the pipe should read `id: 'some_id'`. (note the quotes around the string).

Perhaps this is what you are running into with the plunker demo?

**Comment by Locheed** [comment]
That was the reason for it not working. Not sure when I removed those quotes there because I had them before. :D Thanks.
