### ISSUE TITLE
Multiple pagination uses on one page

### ISSUE THREAD

**Issue by dbogdantech101** [michaelbromley/ng2-pagination#118]
=======

**Angular 2 version**:

ngVer = '@2.4.3';

**ng2-pagination version**:

 'https://rawgit.com/michaelbromley/ng2-pagination/master/dist'

**Description of issue**:

Desire to have more than one paginated list on the same page

**Steps to reproduce**:

Create two instances of pagination with separate page variables  

**Expected result**:

Separate page navigation based on assigned variable 

**Actual result**:

All instances of the navigation effect the other instances 

**Demo**: (if possible, edit [this Plunker demo](http://plnkr.co/edit/JVQMPvV8z2brCIzdG3N4?p=preview) and paste the link to your fork)

http://plnkr.co/edit/H7zFmeU6rae2vCUGWamj?p=preview

Any relevant code:
```

```

**Comment by michaelbromley** [comment]
Hi,

See [this part of the docs](https://github.com/michaelbromley/ng2-pagination#paginatepipe).

Specifically:

> **id** [string] If you need to support more than one instance of pagination at a time, set the id and ensure it matches the id attribute of the PaginationControlsComponent / PaginationControlsDirective

**Comment by dbogdantech101** [comment]
Thanks! Somehow missed that

**Comment by michaelbromley** [comment]
No problem 👍
