### ISSUE TITLE
Support for href attribute on NEXT and PREV buttons

### ISSUE THREAD

**Issue by bharatramnani94** [michaelbromley/ng2-pagination#124]
**Angular 2 version**: 2.2.3

**ng2-pagination version**: 1.0.1

**Description of issue**: Implement mechanism to generate `href` on _NEXT_ and _PREV_ buttons (would be helpful for SEO purposes)

**Expected result**: _NEXT_ and _PREV_ buttons would have a valid `href`

**Actual result**: No `href` attribute present on _NEXT_ and _PREV_ buttons (anchor tags)

**Comment by michaelbromley** [comment]
Hi, 

This is probably a case for creating your own custom controls component using the provided directive - see https://github.com/michaelbromley/ng2-pagination#paginationcontrolsdirective

I want to keep the default PaginationControlsComponent as simple as I can, so any more advanced or unusual use-cases should be handled using the directive.

**Comment by bharatramnani94** [comment]
Right.
I solved my problem by generating the next and previous page URLs by utilising the `getCurrent()` method. Wasn't too difficult, but reported here since I consider it a common use-case, and I think that `a` tags should have valid `href`, or they should be `buttons` instead.

**Comment by 1dot44mb** [comment]
Here is an example code for _next_ button in directive.
This makes the _next_ button a link which can be parsed by robots easily.
```
<a *ngIf="!p.isLastPage()"
    [routerLink]="[]"
    [queryParams]="{ currentPage: p.getCurrent() + 1 }"
    queryParamsHandling="merge">
  {{ nextLabel }}
  <span class="show-for-sr">{{ screenReaderPageLabel }}</span>
</a>
```
