### ISSUE TITLE
Application does not load when binding a variable to the pagination controls

### ISSUE THREAD

**Issue by voicualexandru89** [michaelbromley/ng2-pagination#126]
**Angular 2 version**:
2.4.7
**ng2-pagination version**:
2.0.0
**Description of issue**:
Receiving an error in the console and the application is not loading:
```
> There is no directive with "exportAs" set to "paginationApi" ("6 col-lg-2">
        <pagination-controls [id]="paginationConfig.id"
                             [ERROR ->]#pagination="paginationApi"
                             (pageChange)="pageChanged($event)"
```

**Steps to reproduce**:
When customizing the pagination-controls directive, I add the variable linked to the pagination directive using #p="paginationApi".
**Expected result**:
I am able to customize the control and use the #p variable.
**Actual result**:
The application does not load and the error appears in the console.
**Demo**: 
http://plnkr.co/edit/mS2r4Fb6mg1ZRqmNnnoP?p=preview
Any relevant code:
The pagination control:
```
`<pagination-controls [id]="paginationConfig.id"`
`                             #pagination="paginationApi"`
`                             (pageChange)="pageChanged($event)"`
`                             directionLinks="true"`
`                             autoHide="false">`
`            <nav aria-label="Page navigation">`
`                <ul class="pagination">`
`                    <li class="page-item" [class.disabled]="pagination.isFirstPage()">`
`                        <a class="page-link" href="#" aria-label="Previous" tabindex="{{ pagination.isFirstPage() ? -1 : 1 }}" (click)="pagination.previous()">`
`                            <span aria-hidden="true">&laquo;</span>`
`                            <span class="sr-only">Previous</span>`
`                        </a>`
`                    </li>`
`                    <li class="page-item" *ngFor="let page of pagination.pages" [class.active]="pagination.getCurrent() === page.value">`
`                        <a class="page-link" href="#" (click)="pagination.setCurrent(page.value)">`
`                            {{ page.value }}`
`                            <span class="sr-only">(current)</span>`
`                        </a>`
`                    </li>`
`                    <li class="page-item" [class.disabled]="pagination.isLastPage()">`
`                        <a class="page-link" href="#" aria-label="Next" tabindex="{{ pagination.isLastPage() ? -1 : 1 }}" (click)="pagination.next()">`
`                            <span aria-hidden="true">&raquo;</span>`
`                            <span class="sr-only">Next</span>`
`                        </a>`
`                    </li>`
`                </ul>`
`            </nav>`
`        </pagination-controls>`
```

**Comment by michaelbromley** [comment]
Hi,

You seem to be mixing up the `PaginationControlsComponent` and the `PaginationControlsDirective`. Only the directive exports an `paginationApi`. 

If you wish to create a custom control, use:

```HTML
<pagination-template #p="paginationApi">...</pagination-template>
```

Note that you will need to implement such things as "directionLinks" and "autoHide" yourself. You can use the [default controls](https://github.com/michaelbromley/ng2-pagination/blob/4200c7b12317e871a02828ca93041d515f987b85/src/pagination-controls.component.ts) and [template](https://github.com/michaelbromley/ng2-pagination/blob/4200c7b12317e871a02828ca93041d515f987b85/src/template.ts) code to get an idea of how they are implemented in the default controls.

**Comment by voicualexandru89** [comment]
Thank you very much for the quick response, I now understand how to customize the control. I will get the chance to test it out in the coming weeks.

Thanks a lot for the hard work, the component is great and easy to use.

**Comment by michaelbromley** [comment]
Glad to hear it. I'll close this issue now then. Re-open it if you are still stuck later.

**Comment by voicualexandru89** [comment]
Thanks a lot, I'll be sure to contact you if I can't get past something :)

Thanks,
Alex
