### ISSUE TITLE
Pagination and Links not working as expected

### ISSUE THREAD

**Issue by jtandrew** [michaelbromley/ng2-pagination#127]
**Angular 2 version**:
2.4.5

**ng2-pagination version**:
2.0.0

**Description of issue**:
The data in the list paginates as expected.    The routerLink is not changing the ID's of the items when it paginates.  So when clicking on an item it opens the matching item on the first page.  

**Steps to reproduce**:
Open the application click on Next or on page 2.  It changes the display values of the items in the list.
Click on a list item and it navigates to a component via routerLink.  If you click on the first item it will open item 0 and not item 10

**Expected result**:
Open the application click on Next or on page 2.  It changes the display values of the items in the list.
Click on a list item and it navigates to a component via routerLink.  If you click on the first item it will open item 10

**Actual result**:
Open the application click on Next or on page 2.  It changes the display values of the items in the list.
Click on a list item and it navigates to a component via routerLink.  If you click on the first item it will open item 0 and not item 10

I will add a demo if necessary.   Please let me know if there is an issue or if I need to find a different way to handle my linking capabilities.
Thanks!

**Comment by michaelbromley** [comment]
Hi,

It's hard to help to figure out what is going wrong without at least seeing some code. A demo would be great, but at the minimum show the relevant bits of code.

**Comment by jtandrew** [comment]
Ok here is some of the relevant code.

`<div class="row">
  <div class="col-xs-12">
    <ul class="list-group">
          <leasetool-lease-savings-item *ngFor="let leasesaving of leaseSavings | paginate: {itemsPerPage: 10, currentPage:page, id: '1'}; let i = index" [leasesaving]="leasesaving" [leasesavingId]="i"></leasetool-lease-savings-item>
         </ul>
  </div>
</div>
<div class="row">
  <div class="col-xs-12">
<pagination-controls (pageChange)="page = $event" id="1"
      maxSize="5"
      directionLinks="true"
      autoHide="true">
</pagination-controls>
</div>
</div>`

Please let me know if additional might be needed.

**Comment by michaelbromley** [comment]
I assume the `routerLink` part is inside the `<leasetool-lease-savings-item>` component then? I think the problem might lie with the implementation of that component. If you want to show me the implementation of that component, I might be able to help further.

**Comment by jtandrew** [comment]
Here is what I have on the HTML of that component:
`<a [routerLink]="[leasesavingId]" class="list-group-item clearfix" routerLinkActive="active">
  <div class="pull-left">
    <span class="list-group-item-text">{{leasesaving.site_id}}</span>
  </div>

</a>`

and the ts
`import { Component, Input } from '@angular/core';

import { LeaseSavings } from '../lease-savings';

@Component({
  selector: 'leasetool-lease-savings-item',
  templateUrl: './lease-savings-item.component.html'

})
export class LeaseSavingsItemComponent {
  @Input() leasesaving: LeaseSavings ;
  @Input() leasesavingId: number;


  constructor() { }


}
`
Sorry for the delay in responding.  Thanks for the assistance

**Comment by michaelbromley** [comment]
Ah I see the problem.

The variable `index` which is provided by `ngFor` relates only to the current page. `ngFor` has no knowledge of the pagination - it only knows we are passing it 10 items and it should repeat them. So the indexes for every single page will always be the range 0-9.

To get around this, you will need to calculate the actual ordinal value for each item. This is simply:

```
(itemsPerPage * (currentPage - 1)) + index
```
