### ISSUE TITLE
Add systemjs bundle

### ISSUE THREAD

**Issue by michaelbromley** [michaelbromley/ng2-pagination#13]
Some people might not want to use the commonjs files and may prefer a systemjs (System.register) bundle. This is also useful for testing things out in Plunker, JsBin etc. See the [Angular 2 docs on bundling](https://github.com/angular/angular/blob/ae7d2ab515a3761e14d023c2f2ce8176fe019cd4/modules/angular2/docs/bundles/overview.md#systemjs-loader-users) as a starting point.

**Comment by vazh** [comment]
i'm very noob in angular or even javascript.

can you point out how to use commonjs if i come from angular2 tutorial tour-of-heroes way ?

some links would be nice too ~

**Comment by michaelbromley** [comment]
@vazh Currently this module is only exported in the Commonjs format, so you'll need some kind of build step in order to use it (Webpack or browserify for example). I agree that Webpack etc. are very confusing at first - I only recently got my head around it.

This issue shows my intent to create a systemjs bundle, which might be somewhat easier to use than commonjs (it is the format used on the demo Angular2 Plunkers you might have seen). I've not had time to work on it yet though.

**Comment by vazh** [comment]
@michaelbromley if you can, can you point me to something that resembles angular2 tutorial but in commonjs ?

kind of need some pagination module, but to write it from zero, its going to take some time. and im not sure its going to work like yours anyway. haha.

any suggestion ?

**Comment by michaelbromley** [comment]
@vazh This one looks fairly simple: http://schempy.com/2016/01/19/angular2_webpack_typescript/

There is this: https://angularclass.github.io/angular2-webpack-starter/ - may be a bit heavy going though, but includes everything.

**Comment by michaelbromley** [comment]
This is now done - see https://github.com/michaelbromley/ng2-pagination#systemregister.
