### ISSUE TITLE
Pagination Not Following Directive Re: # of Items Per Page

### ISSUE THREAD

**Issue by darrenbrett** [michaelbromley/ng2-pagination#133]
Hi Michael,

Thanks so much for an amazing tool to handle pagination!

=======

**Angular 2 version**:
@angular/cli: 1.0.0-rc.1

**ng2-pagination version**:
ng2-pagination": "^2.0.1

**Description of issue**:
I am using the pagination code on several components. On a couple of them I see the expected result, where I am filtering 15 results per page, and calculating the total number of pages by passing in the total number of records via an API call.

However, in one component, which is calling the collection where we have the most records (about 10,000 objects), for some reason it's not applying the per page filter properly. To be specific, the results per page is probably a couple hundred, as opposed to 15.

I have triple-checked the code I'm using, and the implementation looks the same for each of the components - so I'm not sure what the issue is with this one particular component -- unless there's some kind of default filter built in to handle really large collections that creates an override?

Here's my component code:

```
    ngOnInit() {
        this.customerService.getAll()
            .subscribe(resRecordsData => this.records = resRecordsData,
            responseRecordsError => this.errorMsg = responseRecordsError);

        this.customerService.getCustomerCount()
            .subscribe(resRecordsData => this.customerCount = resRecordsData,
            responseRecordsError => this.errorMsg = responseRecordsError);

        this.getPage(1);
    }

    getPage(page: number) {
        this.loading = true;
        this.asyncRecords = this.serverCall(this.records, page)
            .do(res => {
                this.total = res.total;
                this.page = page;
                this.loading = false;
            })
            .map(res => res.items);
     }

    serverCall(meals: string[], page: number): Observable<IServerResponse> {
        const perPage = 15;
        const start = (page - 1) * perPage;
        const end = start + perPage;

        return Observable
            .of({
                items: this.records.slice(start, end),
                total: this.customerCount
            });
    }
```

And in my view, I have this:

```  
<tr *ngFor="let record of records | paginate: { id: 'customers', itemsPerPage: 15, currentPage: page, totalItems: customerCount }">...
```

```
                <div *ngIf="!!records && records.length" class="pagination">
                    <pagination-controls class="paginator" (pageChange)="page = $event" id="customers"
                            maxSize="15"
                            directionLinks="true"
                            autoHide="true">
                    </pagination-controls>
                </div>
```

**Comment by michaelbromley** [comment]
Hi,

My first thought when looking through your code, is that I wonder why you are essentially paging the full collection yourself before handing it off to the `PaginatePipe`. If I understand correctly, your code:

1. Gets all customers, and stores them in `records`
2. Gets the total customer count, and stores it in `customerCount`
3. When `getPage()` is called, it calculates the records which should appear on that page, returns a sliced array and the total.
4. This data is then passed to the `PaginatePipe`.

Step 3 is actually the domain on the`PaginatePipe` - that is the main function that it performs. Here is a simplified way of paging all your customers:

```TypeScript
 ngOnInit() {
        this.customerService.getAll()
            .subscribe(resRecordsData => this.records = resRecordsData,
            responseRecordsError => this.errorMsg = responseRecordsError);

        this.customerService.getCustomerCount()
            .subscribe(resRecordsData => this.customerCount = resRecordsData,
            responseRecordsError => this.errorMsg = responseRecordsError);

        this.page = 1;
    }
```

```HTML
<tr *ngFor="let record of records | paginate: { id: 'customers', itemsPerPage: 15, currentPage: page }">...
```

```HTML
<div *ngIf="!!records && records.length" class="pagination">
    <pagination-controls class="paginator" (pageChange)="page = $event" id="customers"
        maxSize="15"
        directionLinks="true"
        autoHide="true">
  </pagination-controls>
</div>
```

If I have misunderstood your intent of you have another reason you need to do it the way you show above, let me know. Otherwise tell me if this approach works better.

**Comment by darrenbrett** [comment]
Thanks, Michael. So, interestingly, just having this in my component:
```
 ngOnInit() {
        this.customerService.getAll()
            .subscribe(resRecordsData => this.records = resRecordsData,
            responseRecordsError => this.errorMsg = responseRecordsError);

        this.customerService.getCustomerCount()
            .subscribe(resRecordsData => this.customerCount = resRecordsData,
            responseRecordsError => this.errorMsg = responseRecordsError);
    }
```
Along with this in my view:

`<tr *ngFor="let record of records | paginate: { id: 'customers', itemsPerPage: 15, currentPage: page }">`

... is sufficient for this to work? 

At first I thought I would need to somehow pass in the length of the array for the pipe to be able to accurately generate the correct number of pages. But it looks like the "let record of records" part of the *ngFor is enough to let the pipe have access to the length of the array. Is this correct?

**Comment by darrenbrett** [comment]
Thanks.  And if you happen to know of a github repo that shows an example with an actual server-side rendering, I'd be interested to see it. Our largest collection has 10,000 objects, and thus probably should be handled in such a way as to not have all 10,000 objects in memory at the same time.
