### ISSUE TITLE
Set itemsPerPage dynamically

### ISSUE THREAD

**Issue by agent0** [michaelbromley/ng2-pagination#136]
Hi,

I was wondering if it is possible to change the itemsPerPage property according to the available space on the screen. I would like to listen for resize events and then calculate, how many items fit on the screen. To this end, I would need to bind the itemsPerPage to a function that calculates the correct number. Is this even possible?

Regards,

Jürgen

**Comment by michaelbromley** [comment]
Sure, it should be possible. As you can see in the [advanced example](http://michaelbromley.github.io/ng2-pagination/#/advanced), you are free to modify the `itemsPerPage` value and the list and pagination links will update automatically.

**Comment by agent0** [comment]
You are, of course, right. Originally, I tried to bind a function to the configuration property and that did not work. Using plain property binding does the trick. Thanks for your help.

**Comment by michaelbromley** [comment]
No problem!
