### ISSUE TITLE
Difficulty using in a shared module

### ISSUE THREAD

**Issue by alsoicode** [michaelbromley/ng2-pagination#138]
**Angular 2 version**: 4.0.0

**ng2-pagination version**: 2.0.1

**Description of issue**: Module doesn't work as expected when imported into a shared module that is imported into other lazy-loaded feature modules.

**Steps to reproduce**:
- Create a shared module and implement Ng2PaginationModule
- import the shared module into a lazy-loaded feature module

**Expected result**:
pagination pipes, directives and components work as expected

**Actual result**:
The pipe 'paginate' could not be found

In my application, I have a hierarchy of feature modules. To share components across these modules, I have imported all common components, pipes, directives, etc, into this shared module.

If I directly import:
 ```
import { PaginatePipe, PaginationService, PaginationControlsDirective } from 'ng2-pagination';
```

in the shared module, it will work as expected, but AOT compilation breaks:

```
Error: Type PaginationControlsDirective is part of the declarations of 2 modules
```

Have you encountered this use case before? If so, what's the solution?

**Comment by michaelbromley** [comment]
Hi,

In one of my own projects I do this and it works for me. Are you making sure you re-export the module? Otherwise the `declarations` will not be made available to the consumers of your shared module:

```TypeScript
@NgModule({
    imports: [
      CommonModule,
      FormsModule,
      HttpModule,
      Ng2PaginationModule
    ],
    declarations: [/* ... */],
    exports: [Ng2PaginationModule, /*... more exports ... */]
})
export class KbuiCommonModule {}
```

**Comment by alsoicode** [comment]
Thanks @michaelbromley I wasn't including the module in the exports.
