### ISSUE TITLE
angular universal error with pagination: .isFirstPage is not a function

### ISSUE THREAD

**Issue by derridHeidegger** [michaelbromley/ng2-pagination#139]
Hi, thanks for contributing!

This project is maintained in my spare time, so in order to help me address your issue as quickly as 
possible, please provide as much of the following information as you can.

-- Michael 

[^ delete this message]

=======

**Angular 2 version**:
universal-cli: 1.0.0-alpha.universal.3
angular-cli: 1.0.0-beta.23
node: 6.10.0
os: win32 x64

**ng2-pagination version**:
^2.0.1

**Description of issue**:
i am trying to implement pagination and i am getting this error:
"EXCEPTION: Uncaught (in promise): Error: Error in ./ProtfolioComponent class ProtfolioComponent - inline template:174:23 caused by: self._PaginationControlsComponent_18_3.context.isFirstPage is not a function
TypeError: self._PaginationControlsComponent_18_3.context.isFirstPage is not a function"

**Steps to reproduce**:

**Expected result**:

**Actual result**:

**Demo**: (if possible, edit [this Plunker demo](http://plnkr.co/edit/JVQMPvV8z2brCIzdG3N4?p=preview) and paste the link to your fork)

Any relevant code:
```
in app.browser.module.ts i import it:
import {Ng2PaginationModule} from 'ng2-pagination';
and adding it to the imports
same with app.node.module.ts

then in my template:
`        <pagination-controls class="paginateit" #pagination (pageChange)="p = $event">

            <div class="custom-pagination">

                <div class="pagination-previous" [class.disabled]="pagination.isFirstPage()">
                    <a *ngIf="!pagination.isFirstPage()" (click)="pagination.previous()">
                       <i class="fa fa-chevron-left" aria-hidden="true"></i> </a>
                </div>

                <div *ngFor="let page of pagination.pages" [class.current]="pagination.getCurrent() === page.value">
                    <a (click)="pagination.setCurrent(page.value)" *ngIf="pagination.getCurrent() !== page.value">
                        <span>{{ page.label }}</span>
                    </a>
                    <div *ngIf="pagination.getCurrent() === page.value">
                        <span>{{ page.label }}</span>
                    </div>
                </div>

                <div class="pagination-next" [class.disabled]="pagination.isLastPage()" *ngIf="pagination.directionLinks">
                    <a *ngIf="!pagination.isLastPage()" (click)="pagination.next()"> <i class="fa fa-chevron-right" aria-hidden="true"></i> </a>
                </div>


            </div>

        </pagination-controls>`

and this on the div that loops:
`<div class="vidcard" *ngFor="let v of vids | paginate: { itemsPerPage: 3, currentPage: p }"  >`
```

**Comment by michaelbromley** [comment]
Hi,

You are getting this error because the `<pagination-controls>` component does not expose such an API. Instead, you should use the [`PaginationControlsDirective`](https://github.com/michaelbromley/ng2-pagination#paginationcontrolsdirective). Follow the example from the docs and it should work as expected.

**Comment by derridHeidegger** [comment]
hi michael
thanks it worked. only now the next link doesn't show, the previous does. this is my code:
`    <pagination-template class="paginateit" #pagination="paginationApi" (pageChange)="p = $event">
            <div class="custom-pagination">

                <div class="pagination-previous" [class.disabled]="pagination.isFirstPage()">
                    <a *ngIf="!pagination.isFirstPage()" (click)="pagination.previous()">
                       <i class="fa fa-chevron-left" aria-hidden="true"></i> 
                    </a>
                </div>

                <div *ngFor="let page of pagination.pages" [class.current]="pagination.getCurrent() === page.value">
                    <a (click)="pagination.setCurrent(page.value)" *ngIf="pagination.getCurrent() !== page.value">
                        <span>{{ page.label }}</span>
                    </a>
                    <div *ngIf="pagination.getCurrent() === page.value">
                        <span>{{ page.label }}</span>
                    </div>
                </div>

                <div class="pagination-next" [class.disabled]="pagination.isLastPage()" *ngIf="pagination.directionLinks">
                    <a *ngIf="!pagination.isLastPage()" (click)="pagination.next()"> 
                        <i class="fa fa-chevron-right" aria-hidden="true"></i> 
                    </a>
                </div>


            </div>
    </pagination-template>`

**Comment by derridHeidegger** [comment]
the issue was this: *ngIf="pagination.directionLinks"
thanks for your help
