### ISSUE TITLE
Does the pagination pipe need to be stateless?

### ISSUE THREAD

**Issue by synapze** [michaelbromley/ng2-pagination#14]
I've created a order by pipe that only refreshes the collection once you paginate. 
Im guessing this has to do with the default stateless nature of pipes in ng2?. 
Possible solutions: 
1. Subscribe to Emitted event that refreshes the collection
2. Add  {pure: false} to the @Pipe decoration config 

Is there any other way I can refresh the collection programatically?

**Comment by michaelbromley** [comment]
The [PaginatePipe is not stateless](https://github.com/michaelbromley/ng2-pagination/blob/master/src/paginate-pipe.ts#L17).

Are you looking for help with authoring your own "orderby" pipe? If so, I think StackOverflow is a good place to ask. It sounds to me like your pipe needs to be stateful by design.

**Comment by synapze** [comment]
My apologies Michael. For some reason I thought the paginate-pipe.ts file didn't have the pure config set to false. My bad.

I'm not looking for authoring my own pipe, I've already created one and works fine on its own. My issue is that when I combine it with the pagination pipe the paginated data does not show the sorted data until I paginate to the next page. I've tried using other sorting pipes, I found on git and they also have the same problem.

I'm basically looking for a way to refresh the paginated data without going to the next/previous page. I can't see anything in the pagination service that could help me do this.

By the way, love your work!

**Comment by synapze** [comment]
Never mind, I worked out the problem. It had to do with the order of the pipes, my orderBy pipe needed to be after the pagination pipe.

I changed this
`*ngFor="#d of data | orderBy : orderBySelection | paginate: paginationConfig"`

to this
`*ngFor="#d of data | paginate: paginationConfig | orderBy : orderBySelection"`

Thanks again, keep up the good work.

**Comment by michaelbromley** [comment]
:+1:
