### ISSUE TITLE
Sugesstion: Change the pagination-controls to not use ID as a way to bind to a pipe

### ISSUE THREAD

**Issue by Tarig0** [michaelbromley/ng2-pagination#143]
I have a want to show one pipe with a paging control above and below the results. Using the ID attribute to link the controls works but is not HTML5 compliant.

http://plnkr.co/edit/RwCQeg1XWLHR3ejwJHmx?p=preview

**Comment by michaelbromley** [comment]
Hi,

One way to get around this is to use a binding, so `[id]="'2'"`. Angular will remove the "id" attribute from the generated HTML in this case.

I'm curious about whether the fact of non-HTML5 compliance causes a particular issue in your case? I hadn't considered this as a problem before.

**Comment by Tarig0** [comment]
I thought there might have been one but I think it was caused by my own code not the pipe -> control link. I figured might as well put an issue up in case there were any possible issues, and since I'm a stickler for conforming to known standards.

I ended up using the [id], since I needed the show my component multiple times on the same page.

**Comment by michaelbromley** [comment]
Ok. I think it is a valid point you raised, but I really want to avoid making a breaking change to the API by renaming the `id` property. For now I will consider the `[id]` workaround as sufficient and close.
