### ISSUE TITLE
Unexpected token <

### ISSUE THREAD

**Issue by dottodot** [michaelbromley/ng2-pagination#16]
I'm a angular newb so probably doing something wrong but after adding this to a previously working component I get the error `Unexpected token <`

```
import {Component, OnInit} from 'angular2/core';
import {PaginatePipe, PaginationControlsCmp, PaginationService} from 'ng2-pagination';
import {User} from '../../../models/user';
import {UserService} from '../../../services/user.service';

@Component({
  selector: 'user-list',
  templateUrl: './app/components/user/list/user-list.html',
  directives: [PaginationControlsCmp],
  pipes: [PaginatePipe],
  providers: [PaginationService]
})
export class UserListComponent {
  users: User[];
  constructor(private _service: UserService) { }
  ngOnInit() {
    this._service.getUsers().then(users => this.users = users);
  }
}
```

**Comment by sangdao-dirox** [comment]
I got the same issue, did anyone fixed it?

**Comment by michaelbromley** [comment]
Hi, you mean you get the error as soon as you add the pagination service/pipe/component to your component, without even using it in the template?

Where is the error reported? Browser console? Is there anything more to that error message?

**Comment by sangdao-dirox** [comment]
Hi,  yes, the error was reported in browser console, this is the error i got:
ng2-pagination:1 Uncaught SyntaxError: Unexpected token <
angular2-polyfills.js:1243 Uncaught SyntaxError: Unexpected token <

**Comment by michaelbromley** [comment]
Thanks. What do you use to bundle your app? Webpack/Browserify/Systemjs etc? Also can you tell me what versions you are using for Angular2, ng2-pagination.

**Comment by sangdao-dirox** [comment]
here is my package.json, hope it can help you reproduce the errror:
{
  "name": "angular2-quickstart",
  "version": "1.0.0",
  "scripts": {
    "start": "concurrent \"npm run tsc:w\" \"npm run lite -c lite-config.js\" ",
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "lite": "lite-server",
    "typings": "typings",
    "postinstall": "typings install"
  },
  "license": "ISC",
  "dependencies": {
    "angular2": "2.0.0-beta.9",
    "angular2-google-maps": "^0.8.1",
    "angular2-modal": "0.0.3",
    "es6-promise": "^3.0.2",
    "es6-shim": "^0.33.3",
    "moment": "^2.11.2",
    "ng2-bootstrap": "1.0.7",
    "ng2-file-upload": "^1.0.0-beta.1",
    "ng2-pagination": "0.0.1-beta.2",
    "reflect-metadata": "0.1.2",
    "rxjs": "5.0.0-beta.2",
    "typescript": "^1.8.0",
    "zone.js": "0.5.15"
  },
  "devDependencies": {
    "concurrently": "^2.0.0",
    "lite-server": "^2.1.0"
  }
}

And here is my index file:
<!DOCTYPE html>
<html>
	<head>
		<base href="/" />
		<title>Exchange Online</title>
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
		<link href="assets/css/style.css" rel="stylesheet">	

		<script src="https://cdnjs.cloudflare.com/ajax/libs/es6-shim/0.33.3/es6-shim.min.js"></script>
	    <script src="https://cdnjs.cloudflare.com/ajax/libs/systemjs/0.19.20/system-polyfills.js"></script>
	    
	    <script src="https://code.angularjs.org/2.0.0-beta.8/angular2-polyfills.js"></script>
	    <script src="https://code.angularjs.org/tools/system.js"></script>
	    <script src="https://npmcdn.com/typescript@1.8.2/lib/typescript.js"></script>
	    <script src="https://code.angularjs.org/2.0.0-beta.8/Rx.js"></script>
	    <script src="https://code.angularjs.org/2.0.0-beta.8/angular2.dev.js"></script>
	    <script src="https://code.angularjs.org/2.0.0-beta.8/router.dev.js"></script>
	    <script src="node_modules/angular2/bundles/http.dev.js"></script>

		
		<script src="node_modules/ng2-bootstrap/bundles/ng2-bootstrap.min.js"></script>
    	<script src="node_modules/angular2-google-maps/bundles/angular2-google-maps.js"></script>
		<script>
			System.config({
				transpiler: 'typescript', 
				typescriptOptions: { emitDecoratorMetadata: true }, 
				packages: {
					'app': {defaultExtension: 'ts'}, 
					'angular2-modal': {defaultExtension: 'ts'},
					'ng2-file-upload': {defaultExtension: 'ts'},
					'config': {defaultExtension: 'ts'} 
				},
    			map: { 
    				'moment': 'node_modules/moment/moment.js', 
    				'angular2-modal': 'node_modules/angular2-modal',
    				'ng2-file-upload': 'node_modules/ng2-file-upload'
    			}
			});
			System.import('app/app.module')
						.then(null, console.error.bind(console));
		</script>
	</head>
	<body>
		<app-container><center>Loading...</center>/app-container>
	</body>
</html>

**Comment by michaelbromley** [comment]
@sangdao-dirox I notice you are using the `angular2-quickstart` seed. I came across this issue: http://stackoverflow.com/questions/34387174/angular-2-quickstart-unexpected-token - does that apply in your case?

@dottodot Is this also the case with you?

**Comment by sangdao-dirox** [comment]
thanks alot

**Comment by dottodot** [comment]
I'm using angular 2.0.0-beta.9

**Comment by shuchangbing** [comment]
rebuild ng2-pagination with System module

**Comment by dottodot** [comment]
After follow the System.register example I got it working.
