### ISSUE TITLE
Excellent work

### ISSUE THREAD

**Issue by rameshbas** [michaelbromley/ng2-pagination#17]
Down loaded your code and added to my project. Worked beautifully with no issues so far!

**Comment by michaelbromley** [comment]
Hi,

Thanks for the kind words! I must point out that opening an issue is not the right place for such a comment - issues are intended to be a place for bug reports and the like. You can always contact authors via email, twitter etc to pass on compliments on their work - we are always very happy to receive such feedback on our projects.
