### ISSUE TITLE
Responsive design without directional buttons only shows a subset of numbers

### ISSUE THREAD

**Issue by rsmith31415** [michaelbromley/ng2-pagination#21]
**Angular 2 version**: 2.0.0-beta.15

**ng2-pagination version**: 0.0.1

**Description of issue**: Responsive design without directional buttons only shows a subset of buttons in `PaginationControlsCmp`.

**Steps to reproduce**: 
Set directionLinks to false: 

```
<pagination-controls (pageChange)="p = $event" #api [directionLinks]="false"></pagination-controls>
```

and look at the page in a small screen

**Expected result**: All the numbers in `PaginationControlsCmp`  should be shown.

**Actual result**: Only a subset of buttons are shown:

![screenshot from 2016-04-23 14-07-00](https://cloud.githubusercontent.com/assets/599274/14763500/bba2405a-095c-11e6-9c89-865c506656ec.png)

**Demo**: (if possible, edit [this Plunker demo](http://plnkr.co/edit/JVQMPvV8z2brCIzdG3N4?p=preview) and paste the link to your fork)

[Demo](http://plnkr.co/edit/Zp8vYdSl8m6Q9MgTRCuw?p=preview)

**Comment by michaelbromley** [comment]
Thanks for the report (and the others). I'll have time to look at and hopefully resolve all of these later this week.

**Comment by rsmith31415** [comment]
Excellent. Thank you!
