### ISSUE TITLE
isFirstPage() triggers "Expression 'm.isFirstPage() has changed after it was checked"

### ISSUE THREAD

**Issue by rsmith31415** [michaelbromley/ng2-pagination#22]
**Angular 2 version**: 2.0.0-beta.15

**ng2-pagination version**: 0.0.1

**Description of issue**: Using the default template for `PaginationControlsCmp`, there is an error ` Expression 'm.isFirstPage() in App@2:10' has changed after it was checked. Previous value: 'false'. Current value: 'true'` after `m.isFirstPage()` is checked.

**Steps to reproduce**: Maybe there is an alternative to this, but having something like `<pagination-controls #m  (pageChange)="p = $event" #api></pagination-controls>` in order to access the API in the template, causes the previous error after `m.isFirstPage()` is evaluated.

**Expected result**: No error is thrown or possibly an alternative to `#m` in the `pagination-controls` element.

**Demo**: (if possible, edit [this Plunker demo](http://plnkr.co/edit/JVQMPvV8z2brCIzdG3N4?p=preview) and paste the link to your fork)

[Demo](http://plnkr.co/edit/lWxZxSoRP54pdmcOBG2T?p=preview)

Thanks

**Comment by michaelbromley** [comment]
This looks like a possible mis-use of the internal api. I'm not sure if this is a good practice or not in terms of Angular 2 idiomatic development.

In your example, you could achieve the same result with `*ngIf="p === 1"`, for example.

**Comment by rsmith31415** [comment]
That's what I thought. `*ngIf="p === 1"`  is definitely much better.

Thank you.
