### ISSUE TITLE
Application becomes unstable after using pure: false in other pipes

### ISSUE THREAD

**Issue by rsmith31415** [michaelbromley/ng2-pagination#23]
**Angular 2 version**: 2.0.0-beta.15

**ng2-pagination version**: 0.0.1

**Description of issue**: Application becomes unstable after using the pattern 

```
*ngFor="#item of objects | somePipe: value | paginate: { itemsPerPage: 10, currentPage: p }"
```
when `somePipe` has the attribute `pure: false`. `value` is supposed to change by the user.

**Steps to reproduce**: Set  `pure: false` to any pipe processing the objects and pass the resulting objects to the pipe `paginate`.

**Expected result**: Application shouldn't become unstable.

**Actual result**: Most actions become really slow and closing the tab is necessary.

**Demo**: (if possible, edit [this Plunker demo](http://plnkr.co/edit/JVQMPvV8z2brCIzdG3N4?p=preview) and paste the link to your fork)

[Demo](http://plnkr.co/edit/E3LjPcyZi06uYK3mrwGV?p=preview). Notice I set by default `pure` to  `true` in the `orderBy` pipe. In a browser session you are not using, change it to `false`. After this, click on the "next" or "previous" buttons or click on the select menu to change the order of the items.

**Comment by michaelbromley** [comment]
Strange. When the other pipe is impure, the PaginatePipe gets continuously invoked, which is what crashes the browser.

Spent a bit of time looking into it but no fix yet. Will have to re-visit.

**Comment by rsmith31415** [comment]
@michaelbromley Thank you. I [confirmed](http://plnkr.co/edit/kDxr7TxB8s7WU33kDUX5?p=preview) that the latest version of ng2-pagination and Angular 2.0.0.-rc.1 are working as expected with `pure: false`.
