### ISSUE TITLE
number: number returns NaN

### ISSUE THREAD

**Issue by baneetgrover** [michaelbromley/ng2-pagination#29]
Hello,
For some reason $event returns NaN. Please see my code below.

**Angular 2 version**: 2.0.0-beta.17

**ng2-pagination version**: 0.2.0

**Description of issue**: When triggering function (pageChange)="onPageChanged($event)", $event returns NaN instead of the page number.

**Steps to reproduce**: Click on Next in the pagination. (no numbers showing, just next)

**Expected result**: Receive a page number

**Actual result**: Receiving NaN

**Demo**: (if possible, edit [this Plunker demo](http://plnkr.co/edit/JVQMPvV8z2brCIzdG3N4?p=preview) and paste the link to your fork)

Any relevant code:

```
import 'reflect-metadata';
import {Component} from 'angular2/core';
import {Parties} from '../../../collections/parties';
import {PartiesForm} from '../parties-form/parties-form';
import {RouterLink} from 'angular2/router';
import {MeteorComponent} from 'angular2-meteor';
import {LoginButtons, InjectUser} from 'angular2-meteor-accounts-ui';
import {ReactiveVar} from 'meteor/reactive-var';
import {PaginationService, PaginatePipe, PaginationControlsCmp} from 'ng2-pagination';
//import {Counts} from 'meteor/tmeasday:publish-counts';

@Component({
    selector: 'parties-list',
    templateUrl: '/client/views/parties-list/parties-list.html',
    directives: [PartiesForm, RouterLink, LoginButtons, PaginationControlsCmp],
    pipes: [PaginatePipe],
    providers: [PaginationService]
})

@InjectUser()

export class PartiesList extends MeteorComponent {
    parties: Mongo.Cursor<Party>;
    pageSize: number = 10;
    curPage: ReactiveVar<number> = new ReactiveVar<number>(1);
    nameOrder: ReactiveVar<number> = new ReactiveVar<number>(1);
    partiesSize: number = 0;
    location: ReactiveVar<string> = new ReactiveVar<string>(null);
    user: Meteor.User;
    
    constructor() {
        super();
        this.autorun(() => {
            let options = {
                limit: this.pageSize,
                skip: (this.curPage.get() - 1) * this.pageSize,
                sort: {name: this.nameOrder.get()}
            };
            this.subscribe('parties', options, this.location.get(), () => {
                this.parties = Parties.find({}, {sort: {name: this.nameOrder.get() }});
            }, true);
        });
//        this.autorun(() => {
//            this.partiesSize = Counts.get('numberOfParties');
//        }, true);
    }

    removeParty(party) {
        Parties.remove(party._id);
    }
    
    search(value: string) {
        this.curPage.set(1);
        this.location.set(value);
    }

    onPageChanged(page: number) {
//        console.log(page);
        this.curPage.set(page);
    }
}
```

**Comment by andyrue** [comment]
I'm experiencing the same thing, same versions. No page numbers showing and $event returning NaN. It seems to be ignoring the `itemsPerPage` number as well for me.

**Comment by michaelbromley** [comment]
Thanks for the report. I'll look into it as soon as I get some time.

**Comment by michaelbromley** [comment]
Can you show me the view markup too? (both of you)

**Comment by andyrue** [comment]
Right now I have a static number in itemsPerPage just to see if I could get anywhere but it was still showing all the items. 

```
<ul>
    <li *ngFor="let party of parties | paginate: {currentPage: 1, itemsPerPage: 1}">
      <a [routerLink]="['/PartyDetails', {partyId: party._id}]">{{party.name}}</a>
      <p>{{party.description}}</p>
      <p>{{party.location}}</p>
      <button (click)="removeParty(party)">X</button>
    </li>
  </ul>
<pagination-controls (pageChange)="onPageChanged($event)"></pagination-controls>
```

**Comment by baneetgrover** [comment]
```
    <ul>
        <li *ngFor="let party of parties | paginate:{itemsPerPage: pageSize, currentPage: 1, totalItems: 30}">
            <a [routerLink]="['/PartyDetails', {partyId: party._id}]">{{party.name}}</a>
            <p>{{party.description}}</p>
            <p>{{party.location}}</p>
            <button (click)="removeParty(party)">X</button>
        </li>
    </ul>
    <pagination-controls (pageChange)="onPageChanged($event)"></pagination-controls>
```

**Comment by andyrue** [comment]
Hi Michael,

I think this is a case of us not fully reading the manual. :) I'm going to guess @baneetgrover was also working through the meteor-angular2 tutorial. Seems we need to use the angular2-pagination package instead of yours? I'm not sure why but I got it working that way.

**Comment by michaelbromley** [comment]
Ah okay. That makes sense. 

As far as I know, @urigo forked this lib because (at the time) it was not feature-complete and ready for inclusion in the tutorial. I have no idea about what is different in that version, but I guess they are the reason that this lib breaks for you.

**Comment by farzaneHashemi** [comment]
despite this issue is closed but I thought maybe my solution to this issue could help someone somewhere in the world :D 

since I used to have more than one table with pagination in my html page, I had to specify my pagination tag with an `id` attribute, but I forgot to put it on my `<tr>` tag as well, and that was the problem which used to cause NaN value for my `$event` . here is my code:
```
 <table>
<tbody>
    <tr *ngFor="let request of requests | paginate: { itemsPerPage: 10, currentPage: p2, id: 'history' }; let i = index">
                                  // put your <td> tags here...
    </tr>
</tbody>
</table>
<pagination-controls previousLabel="pre" nextLabel="next" (pageChange)="p2 = $event" maxSize="9" directionLinks="true" id="history"></pagination-controls>
```

**Comment by warriorkitty** [comment]
If you are here because of googling (like me), it worked after adding totalItems. Here is an example:

```javascript
<div class="col-sm-6 col-md-4 item mt-3"
            *ngFor="let p of collection | paginate: { itemsPerPage: 25, currentPage: 1, id: 'history', totalItems: 100 };">
</div>

<pagination-controls *ngIf="vm"
        (pageChange)="loadCollection({ page: $event })"
        id="history">
</pagination-controls>
```

If component loaded buttons previous & next without the **numbers**, $event gave NaN. After adding totalItems, $event is a number, even if you click on previous or next button.
