### ISSUE TITLE
about updating to angular version 2.0.0-rc.1

### ISSUE THREAD

**Issue by YoungJoonji** [michaelbromley/ng2-pagination#30]
Hi, thanks for contributing!

This project is maintained in my spare time, so in order to help me address your issue as quickly as 
possible, please provide as much of the following information as you can.

-- Michael 

Hi.

I use ng2 pagination for developing angular 2.

well. angular team updated angular version to 2.0.0-rc.1.

I hope to update ng-pagination with angualr 2.0.0-rc.1.

thank you. Have a nice day~~~

=======

**Angular 2 version**: 2.0.0-rc.1

**ng2-pagination version**: 0.0.1-beta.2

**Description of issue**: supporting angular version 2.0.0-rc.1

**Steps to reproduce**:

**Expected result**: version up ng2-pagination suppoting angular version 2.0.0-rc.1

**Actual result**: Thank you very much? :)

**Demo**: (if possible, edit [this Plunker demo](http://plnkr.co/edit/JVQMPvV8z2brCIzdG3N4?p=preview) and paste the link to your fork)

Any relevant code:
```

```

**Comment by sdornan** [comment]
I'm getting the following message when trying to use the plugin as described with rc.1:

`No Directive annotation found on PaginationControlsCmp`

**Comment by michaelbromley** [comment]
v0.3.0 just published, compatible with Angular2 rc.1!

https://www.npmjs.com/package/ng2-pagination

**Comment by stojankukrika** [comment]
:+1:
