### ISSUE TITLE
onPageChange

### ISSUE THREAD

**Issue by RicardoVaranda** [michaelbromley/ng2-pagination#34]
Hi guys, just wondering if something like this is available in the current api, I know you can use it in the directive like (pageChange)="p = $event", but this feature could prove to be quite handy to be able to detect a onChange event with the page number etc.

**Comment by michaelbromley** [comment]
Hi,

I'm afraid I don't quite understand what you are asking for. Could you provide some example code that you are suggesting?

**Comment by michaelbromley** [comment]
I'm closing this issue because further data was needed but was not provided. If you want to continue the thread, feel free to re-open.
