### ISSUE TITLE
Property change within paginated item does not update view

### ISSUE THREAD

**Issue by jwong-dayspring** [michaelbromley/ng2-pagination#35]
**Angular 2 version**: 2.0.0-rc.1

**ng2-pagination version**: 0.3.0

**Description of issue**: Change within paginated item does not update view. 

**Steps to reproduce**: With a list of objects to paginate, update property within one of the objects.

**Expected result**: View updates to show the new value.

**Actual result**: View does not update

**Demo**: http://plnkr.co/edit/LL6ubp7KCpytGmjV7cBO?p=preview

Click "update first" and it should change "item 1" to "first". With paginate, it does not update. If you remove paginate, it works.

**Comment by michaelbromley** [comment]
Thanks for the report and clear demo. Please see [this comment](https://github.com/michaelbromley/ng2-pagination/pull/36#issuecomment-223217879) - I am going to try to find a better solution which is not so brittle.

**Comment by michaelbromley** [comment]
Update to 0.3.1 for fixed version :) https://www.npmjs.com/package/ng2-pagination

**Comment by jwong-dayspring** [comment]
Thanks for the fix!
