### ISSUE TITLE
Updating the browser address bar when paginating

### ISSUE THREAD

**Issue by Megalepozy** [michaelbromley/ng2-pagination#37]
**Angular 2 version**:
RC.1
**ng2-pagination version**:
0.3.0
**Description of issue**:
Updating of the browser address bar doesn't get updated while paginating, this in turn doesn't allow users to easily share links of specific pages
**Steps to reproduce**:
Just paginate between pages of results
**Expected result**:
the address bar should get updated, for ex. www.example.com/articles should be updated to www.example.com/page/2 when a user paginate to the second page (the url addition of "page/#" should be customizable as its also an SEO issue).

It will be even better if this feature will be optional so the dev could decide if he want it or not.
**Actual result**:
The address bar (and also the browser history) doesn't change when paginating 
**Demo**: 
I guess no demo is needed, feel free to let me know otherwise

Thanks a lot for this project!

**Comment by michaelbromley** [comment]
Hi,

This is beyond the scope of this module - it is too application-specific to generalize and still be useful. The application developer needs to solve this problem separately.
