### ISSUE TITLE
Pipe not support Mongo cursor as Collections

### ISSUE THREAD

**Issue by euclid1990** [michaelbromley/ng2-pagination#38]
Now, I am following this tutorial: http://www.angular-meteor.com/tutorials/socially/angular2/search-sort-pagination-and-reactive-vars for sorting and paginate variable `users: Mongo.Cursor<any> = null;`
Although I have set totalItems = 100, but your plugin display nothing
![selection_092](https://cloud.githubusercontent.com/assets/5584709/15733186/bbeca562-28ad-11e6-9213-534998074843.png)

I try to debug, and found that problem in file: `node_modules/ng2-pagination/dist/paginate-pipe.js`
```
PaginatePipe.prototype.transform = function (collection, args) {
    // When an observable is passed through the AsyncPipe, it will output
    // `null` until the subscription resolves. In this case, we want to
    // use the cached data from the `state` object to prevent the NgFor
    // from flashing empty until the real values arrive.
    if (args instanceof Array) {
        // compatible with angular2 before beta16
        args = args[0];
    }
    if (!(collection instanceof Array)) {
        var _id = args.id || this.service.defaultId;
        if (this.state[_id]) {
            return this.state[_id].slice;
        }
        else {
            return collection;
        }
    }
    var serverSideMode = args.totalItems !== undefined;
    var instance = this.createInstance(collection, args);
    var id = instance.id;
    var start, end;
    var perPage = instance.itemsPerPage;
    this.service.register(instance);
    if (!serverSideMode && collection instanceof Array) {
        perPage = perPage || LARGE_NUMBER;
        start = (instance.currentPage - 1) * perPage;
        end = start + perPage;
        var isIdentical = this.stateIsIdentical(id, collection, start, end);
        if (isIdentical) {
            return this.state[id].slice;
        }
        else {
            var slice = collection.slice(start, end);
            this.saveState(id, collection, slice, start, end);
            this.service.change.emit(id);
            return slice;
        }
    }
    // save the state for server-side collection to avoid null
    // flash as new data loads.
    this.saveState(id, collection, collection, start, end);
    return collection;
};
```
The main proplem in this code: It make function return and not run `this.service.register(instance);`
```
    if (!(collection instanceof Array)) {
        var _id = args.id || this.service.defaultId;
        if (this.state[_id]) {
            return this.state[_id].slice;
        }
        else {
            return collection;
        }
    }
```
Pagination pipe simply won't know how to calculate its size when collection not is Array

Can you support more type of collections ? Or tell me the way to set totalItems of PaginationService in this case !

**Comment by michaelbromley** [comment]
Hi - I'm not sure I understand something - why would you want to generate pagination links for a "collection" which is `null`? 

Another thought - would it work to have something like this?

```HTML
<tr *ngFor="let item of (users || []) | paginate: config">...</ul>
```

**Comment by michaelbromley** [comment]
I'm closing this issue because further data was needed but was not provided. If you want to continue the thread, feel free to re-open.

**Comment by euclid1990** [comment]
@michaelbromley Ok, I have been resolved this problem by inject `paginationService` in construct and `register`  custom **config**
