### ISSUE TITLE
Custom template bug

### ISSUE THREAD

**Issue by RaulMo7** [michaelbromley/ng2-pagination#43]
You have a bug with a custom template in live demo, check this:

![image](https://cloud.githubusercontent.com/assets/7596164/15941991/1bafd920-2e48-11e6-9cc3-9a1190d8bf00.png)

Why is a custom template when the template is default and is not overwritten?

Thanks

**Comment by pankajsoninagarro** [comment]
I face same issue

**Comment by michaelbromley** [comment]
It's broken again in the rc.4. I'm working on a fix, will probably be out later this week.

**Comment by pankajsoninagarro** [comment]
Hi I am using rc.3. during first time load it is working fine. But once i will show and hide the pagination based on condition then default pagination style will appear with the custom one.

**Comment by michaelbromley** [comment]
I cannot see this behaviour now (latest version is for rc.6). Please re-open if you run into it with the latest angular and ng2-pagination versions.
