### ISSUE TITLE
404 Not found

### ISSUE THREAD

**Issue by tonywong625** [michaelbromley/ng2-pagination#44]
I followed the installation guide, however I am getting the following error:

(index):46 Error: Error: XHR error (404 Not Found) loading http://localhost:3000/ng2-pagination(…)

The module has installed properly into node_modules folder.

I notice someone else was also having the same issue on Stackoverflow: http://stackoverflow.com/questions/37391604/ng2-pagination-failed-to-load-resource-the-server-responded-with-a-status-of-40

**Comment by michaelbromley** [comment]
Hi,

What method of module loading do you use? SystemJS, Webpack etc.. Please provide some more details of your build and I'll be better able to advise.

**Comment by tonywong625** [comment]
Using systemjs

**Comment by michaelbromley** [comment]
Okay. Please take a look at them Plunker demo for an example for how to use it with systemjs: http://plnkr.co/edit/JVQMPvV8z2brCIzdG3N4?p=preview

Note - You need to load the bundle file in your index.html:

```
<script src="path/to/ng2-pagination/dist/ng2-pagination-bundle.js"></script>
```

And then when you import it, just write 

```
import {PaginationControlsCmp, PaginatePipe, PaginationService} from 'ng2-pagination';
```

**Comment by tonywong625** [comment]
Hey Michael,

Thanks for the info, it is working now.

Tony

**Comment by scottmizo** [comment]
You can also configure systemjs to pull the correct files without having to add the ng2-pagination-bundle to your index.html:

`System.config({ 
    map: {'ng2-pagination': 'pathToSource/ng2-pagination'},  
    packages: { 'ng2-pagination ': { main: 'index.js', defaultExtension: 'js'}
})`

From there it is:

`import {PaginationControlsCmp, PaginatePipe, PaginationService} from 'ng2-pagination';`
