### ISSUE TITLE
Pagination component appears twice when using custom template

### ISSUE THREAD

**Issue by DanielMcAssey** [michaelbromley/ng2-pagination#45]
**Angular 2 version**: 2.0.0-rc.1

**ng2-pagination version**: 0.3.2

**Description of issue**: When using a custom template on pagination, the pagination tool appears twice, one is the templated pagination and the other is the original pagination

**Steps to reproduce**: Add pagination with custom template

**Expected result**: A single templated pagination component

**Actual result**: 2 pagination components, 1 templated and the other default template

**Demo**: (if possible, edit [this Plunker demo](http://plnkr.co/edit/JVQMPvV8z2brCIzdG3N4?p=preview) and paste the link to your fork)

Any relevant code:
```

```
![chrome_2016-06-09_15-28-00](https://cloud.githubusercontent.com/assets/3080979/15959791/4f1a74b2-2ef4-11e6-9b99-c79fca910d1d.png)

**Comment by DanielMcAssey** [comment]
Nevermind saw that you fixed this recently

**Comment by DanielMcAssey** [comment]
This has now started happening again since 0.3.4

**Comment by michaelbromley** [comment]
Hi, can you reproduce? I do not see this behaviour: http://plnkr.co/edit/vpvDEBPanuBmfvMk3JJ2?p=preview

**Comment by DarkDrim** [comment]
+1. I have the same thing happening:
![1](https://cloud.githubusercontent.com/assets/3989836/16332309/fedb579a-39fd-11e6-8467-91d4ac48fdf9.png)

**Comment by DarkDrim** [comment]
I discovered that it occurs during the installation id: 'xxx' in the configuration.

**Comment by DarkDrim** [comment]
If you put in the config default "totalItems: 1" - the second pagination disappears. But I think this is not the best solution.

**Comment by AndresRicardoTorres** [comment]
+1 I have this behaviour on RC3, but not in RC1

**Comment by michaelbromley** [comment]
@DarkDrim Thanks for the Plunker demo. I can see that there is an `*ngIf` on the `pagination-controls` component. If you remove that, then the default template does not show up.

I'm not exactly sure why that is, but the general issue is to do with the fact that I recently switched the component's change detection strategy to OnPush - which has massive positive performance effects, but somehow causes this issue. 

Not had time to upgrade and test on rc3 yet, and I will be away next week so will not be able to fix until the following week.

**Comment by DanielMcAssey** [comment]
Any luck with this on RC.4?

**Comment by michaelbromley** [comment]
I am working on upgrading an app to rc.4 and when done, I will upgrade this library, hopefully by tomorrow. I'll see if this is still an issue then.

**Comment by DarkDrim** [comment]
@michaelbromley There are hopes that this bug will be fixed in the near future?

**Comment by michaelbromley** [comment]
@DarkDrim Yes, I am in progress on it. I have limited time to work on this project, but I am confident there will be a new version published later this week (thursday or friday) with a fix for this.

**Comment by michaelbromley** [comment]
Should be fixed now in v0.3.5.
