### ISSUE TITLE
typings install issue

### ISSUE THREAD

**Issue by ADringer** [michaelbromley/ng2-pagination#49]
**Angular 2 version**: 2.0.0-rc.1

**ng2-pagination version**: 0.3.3

**Description of issue**: I've using the [Angular2-seed project](https://github.com/mgechev/angular2-seed) and when I try adding ng-2pagination to the project it errors with the following when doing the post install script:

> c:\Temp\angular2-seed-master>npm install ng2-pagination --save

> ng2-pagination@0.3.3 postinstall c:\Temp\angular2-seed-master\node_modules\ng2
-pagination
> npm run typings:install

> ng2-pagination@0.3.3 typings:install c:\Temp\angular2-seed-master\node_modules
\ng2-pagination
> node node_modules/typings/dist/bin install

> module.js:327
>    throw err;
   

> Error: Cannot find module 'c:\Temp\angular2-seed-master\node_modules\ng2-paginat
ion\node_modules\typings\dist\bin'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

**Steps to reproduce**:

1. Clone the latest version of Angular2-seed
2. run 'npm-install' to install the current packages
3. run 'npm install ng2-pagination --save' 
4. Error appears in output window

**Comment by michaelbromley** [comment]
Thanks. That postinstall step is only needed for the Travis CI build. Moved it into the travis file now. v0.3.4 just published.

**Comment by ADringer** [comment]
Great thanks, just tried it with the latest version and it's installing fine. Thanks for the quick fix.
