### ISSUE TITLE
Unexpected token < when setting up pagination

### ISSUE THREAD

**Issue by padjodev** [michaelbromley/ng2-pagination#51]
Hi, thanks for contributing!

This project is maintained in my spare time, so in order to help me address your issue as quickly as 
possible, please provide as much of the following information as you can.

-- Michael 

=======

**Angular 2 version**:
RC1

**ng2-pagination version**:
Not sure, I just downloaded it via npm 

**Description of issue**:
(index):40 Error: SyntaxError: Unexpected token <
	    at Object.eval (http://localhost:3000/src/tmp/app/components/Blog/list/BlogListComponent.js:15:24)
	    at eval (http://localhost:3000/src/tmp/app/components/Blog/list/BlogListComponent.js:44:4)
	    at eval (http://localhost:3000/src/tmp/app/components/Blog/list/BlogListComponent.js:45:3)
	Evaluating http://localhost:3000/ng2-pagination
	Evaluating http://localhost:3000/src/tmp/app/components/Blog/list/BlogListComponent.js
	Evaluating http://localhost:3000/src/tmp/app/components/init/InitComponent.js
	Evaluating http://localhost:3000/src/tmp/app/main.js
	Error loading http://localhost:3000/src/tmp/app/main.js(anonymous function) @ (index):40g @ es6-shim.js:2194(anonymous function) @ es6-shim.js:2182ZoneDelegate.invoke @ zone.js:323Zone.run @ zone.js:216(anonymous function) @ zone.js:571ZoneDelegate.invokeTask @ zone.js:356Zone.runTask @ zone.js:256drainMicroTaskQueue @ zone.js:474ZoneTask.invoke @ zone.js:426

**Steps to reproduce**:
No steps really I use the code in the examples but when I add in the directive for PaginationControlsCmp i get the above error

**Comment by rolandoldengarm** [comment]
Using system.js?
"Unexpected token < " is in most cases related to wrong system.js configuration in my experience.

**Comment by padjodev** [comment]
Really, yeah I'm using system js.. But can't quite work out how to set this
up though
