### ISSUE TITLE
Error Handling in Server Example

### ISSUE THREAD

**Issue by kiwiingenuity** [michaelbromley/ng2-pagination#58]
I have your server sample up and working as expected.

Can you give us a tip on how to handle errors with the async call.  If the server throws and error I would like to present the user with a message.  Usually I would handle this in the subscribe, but there is now subscribe in this case?

__Allan

**Comment by michaelbromley** [comment]
Hi,

That is out of the scope of this module, since it is a general Angular question. A quick search turned up this answer: http://stackoverflow.com/questions/38230152/error-handling-with-angular2-async-pipe

Over to you to try out the recommendations.
