### ISSUE TITLE
Pagination controls can not be before the paginated content

### ISSUE THREAD

**Issue by mfodor** [michaelbromley/ng2-pagination#6]
If I place `<paginagtion-controls ... />` before the element with `paginate` pipe the app crashes with
```
TypeError: Cannot read property 'currentPage' of undefined
    at PaginationControlsCmp.updatePages (pagination-controls-cmp.js:60)
    at PaginationControlsCmp.ngOnChanges (pagination-controls-cmp.js:82)
```
because `this.service.getInstance(this.id)` returns with `undefined` instead of the pagination service instance.

**Comment by michaelbromley** [comment]
Thanks, I'll look into this as soon as I get time to work on it.

**Comment by michaelbromley** [comment]
Please see the latest version (beta.1), this should be fixed.
