### ISSUE TITLE
Features: go first page, go last page

### ISSUE THREAD

**Issue by nunos7** [michaelbromley/ng2-pagination#62]
Hi, 
I'm using custom template and i need to show two links, "go to first page" and "go to last page". 
The component already has this feature? How can i do that?

thks,
NS

**Comment by michaelbromley** [comment]
Hi,

Yes, there is actually an undocumented API method, `getLastPage()` which you can use:

```HTML
<!-- going to first page is easy, since it is always 1 -->
<a (click)="api.setCurrent(1)">go to first page</a>
<!-- going to last page could be done like this: -->
<a (click)="api.setCurrent(api.getLastPage())">go to last page</a>
```

I will update the docs to include this method.
