### ISSUE TITLE
Serial Number on rows

### ISSUE THREAD

**Issue by AJMalik007** [michaelbromley/ng2-pagination#63]
I am using ng2-pagination in my angular 2 application now I want to show serial number on rows increment to all the rows from 1 to nth row. I write some code but it only shows 1 to 10 number and it loads again from 1 to 10 number when I go to next page and so on.
my table show 10 records per page.
**my code.**
`<tr *ngFor="let user of _data | paginate: config; let i=index">
                <td>{{i+1}}</td>
                <td>{{user.FirstName}}</td>
                <td>{{user.LastName}}</td>
                <td>{{user.Email}}</td>
            </tr>`
**Image 1 Page**
![image](https://cloud.githubusercontent.com/assets/9094444/17182893/b8fb43ba-543e-11e6-83fe-e8e522e8b186.png)

**Image 2 Page**
![capture](https://cloud.githubusercontent.com/assets/9094444/17182948/f6c68f2e-543e-11e6-8a86-dc810cdb7c75.PNG)

**Comment by michaelbromley** [comment]
Yes, this the expected behaviour of the `ngFor` "index" value. It has no awareness of its place in a paginated series of lists.

So the way you can do it is like this:

```HTML
<tr *ngFor="let user of _data | paginate: config; let i=index"> 
  <td>{{ (config.currentPage - 1) * config.itemsPerPage + index +1 }}</td> 
  <td>{{user.FirstName}}</td> 
  <td>{{user.LastName}}</td> 
  <td>{{user.Email}}</td> 
</tr>
```

**Comment by AJMalik007** [comment]
I use this line of code but it shows NaN
`{{ (config.currentPage - 1) * config.itemsPerPage + index +1 }}`

**Comment by AJMalik007** [comment]
Issue Resolved by replacing index to i 
`{{ (config.currentPage - 1) * config.itemsPerPage + i +1 }}`
great thanks

**Comment by bhagatshubham1994** [comment]
In my case where to write **{{ (config.currentPage - 1) * config.itemsPerPage + i +1 }}**

also where should I write paginate: **config** as the paginate 


<tr *ngFor="let shipment of finalShipmentList | paginate:{ itemsPerPage:10, currentPage: p }; let i = index">
        <td [routerLink]= "['/truckDetails',shipment.truckNumber,shipment.ShipmentID]">{{i + 1}}</td>
      </tr>

      <pagination-controls (pageChange)="p=$event"></pagination-controls>
