### ISSUE TITLE
How do I override the css?

### ISSUE THREAD

**Issue by amnporter** [michaelbromley/ng2-pagination#64]
I've tried to override the font size/font/colors/etc and have had no luck. Also, it doesn't look like you can currently replace the 'Previous' or 'Next' text, is that correct.

I've tried a couple of the examples below to no avail. Am I doing something wrong?
```
[override] .bulkResults pagination-controls .ng2-pagination li {
  -moz-user-select: none;
  -webkit-user-select: none;
  -ms-user-select: none;
  font-size: 0.875rem;
  margin-right: 0.0625rem;
  border-radius: 0;
  color: #ffffff;
}

.bulkResults pagination-controls a:hover,
.bulkResults pagination-controls button:hover {
  background: #ffa500;
}
```

**Comment by michaelbromley** [comment]
I guess this is due to the encapsulation that Angular applies to the styles.

You could try something like:

```CSS
.bulkResults pagination-controls /deep/ .ng2-pagination li {
 // your styles...
```

The `/deep/` selector tells Angular to "reach in" to the component and apply styles to that too.

**Comment by amnporter** [comment]
Thanks. I've got the styles working. Is there any way to change to the text of 'Previous' and 'Next' to support translations.

**Comment by wadel86** [comment]
Hi @amnporter, did you managed to change the style only using /deep/ selector ?

**Comment by amnporter** [comment]
@wadel86, I actually was missing a level in my css. I needed to go down one more level. I didn't need any special keywords like [override] or /deep/.

**Comment by wadel86** [comment]
@amnporter, thank you, I have to check my css too I guess.

**Comment by guybartal** [comment]
pagination-controls /deep/ .ng2-pagination li {
 // your styles...

worked for me! thanks!

**Comment by akshay27395** [comment]
I tried this - 

component.css


```
.my-pagination /deep/ .ngx-pagination .current {
  background: #0b3c6d  !important;
 
}

```

component.html

```
<div style="padding-left:250px;">
                    <pagination-controls class="my-pagination" (pageChange)="p= $event"></pagination-controls>
                  </div>
```


But still not working

**Comment by AlexKuskov** [comment]
@akshay27395, looks like /deep/ is deprecated (https://angular.io/guide/component-styles#deprecated-deep--and-ng-deep). You can try to use ::ng-deep instead:
```
.my-pagination::ng-deep .ngx-pagination .current {
  background: #0b3c6d  !important;
 
}
```

**Comment by EloyRoura** [comment]
Hi there, I know this is an old issue, but still getting troubles to change some part of the css with angular 8.
backgrounds are getting override like this:
::ng-deep .ngx-pagination .current {
    background: red;
  }
::ng-deep .ngx-pagination{
    background: white;
  }

however, when I try to change the color of the text, only the active element gets override, but not the rest. Below the code for that:
::ng-deep .ng2-pagination li {
    color: gray;
  }

Any idea why this is not working?

**Comment by softwareinnovations** [comment]
See if these help. The class for my pagination is my-pagination, so adjust accordingly.

/* sets font color for pagination to white */
.my-pagination::ng-deep .ngx-pagination a {
  color: white;
}

/* sets font color for number color when hovering */
.my-pagination::ng-deep .ngx-pagination a:hover {
  color: red;
}

/* sets font color for disabled previous or next words */
.my-pagination::ng-deep .ngx-pagination .disabled {
  color: white !important;
}
