### ISSUE TITLE
Unable to use multiple pagination on the same page

### ISSUE THREAD

**Issue by Carol-Dsouza** [michaelbromley/ng2-pagination#65]
Hi,

I'm trying to use more than one pagination on the same page:
eg:

    <div class="row">
      <div class="medium-8 medium-offset-2 columns">
        <h2 class="subheader"></h2>
        <ul>
          **<li *ngFor="let item1 of collection1 | paginate: {id:'test1', itemsPerPage: 10, currentPage: p }">{{ item1 }}</li>**
        </ul>

        <pagination-controls id="test1" (pageChange)="p = $event" #api>
        </pagination-controls>
      </div>
    </div>
    
     <div class="row">
      <div class="medium-8 medium-offset-2 columns">
        <h2 class="subheader"></h2>
        <ul>
          **<li *ngFor="let item2 of collection2 | paginate: {id:'test2', itemsPerPage: 10, currentPage: p }">{{ item2 }}</li>**
        </ul>

        <pagination-controls id="test2" (pageChange)="p = $event" #api>
        </pagination-controls>
      </div>
    </div>
  

But, I'm not able to achieve it even though I've given unique id's to both the pagination.
Am I missing something here?

Thanks in advance.
Carol.

**Comment by michaelbromley** [comment]
>  I'm not able to achieve it

Can you elaborate on this? What exactly occurs? Any error messages?

Also, if you can reproduce this in a plunk (http://plnkr.co/edit/JVQMPvV8z2brCIzdG3N4?p=preview), I'll probably be able to help you quite quickly.

**Comment by Carol-Dsouza** [comment]
Hi,

When I click the pagination link/s for the 1st pagination, it simultaneously affects the pagination links of the second pagination & vice versa.

The following is the plunker link wherein I've tried to implement it.
http://plnkr.co/edit/yI2Yc9503tn9HyaCg6xN?p=preview

Thank you.

**Comment by michaelbromley** [comment]
Thanks for the demo. 

The issue here is that you are using the same variable, `p` as the value of `currentPage` for both instances. This is why they are "joined". Try using a different variable for each and it should work.

**Comment by Carol-Dsouza** [comment]
Hi,

Thanks for the solution..

The pagination for multiple instances on same page is working fine now...

**Comment by irrfan13** [comment]
i am using different id for currentpage , totalItems an ditemsperpage i am still not able to show both paginations at a time
