### ISSUE TITLE
when click the page doesn´t change on custom template 

### ISSUE THREAD

**Issue by Ragnarok99** [michaelbromley/ng2-pagination#67]
Hi, I'm having some problems using the demo custom template pagination from docs, when i click a page´s number or even the arrow to see another page doesn´t works, I don´t know if i'm missing something, by the way, i'm using angular rc5.

plunker showing the problem here: http://plnkr.co/edit/nNkU7KEa73sk5EOASKIF?p=preview

Thanks.

**Comment by visikov** [comment]
@Ragnarok99 Were you able to solve this?

**Comment by Ragnarok99** [comment]
@visikov no, do you have it too?

**Comment by michaelbromley** [comment]
You have an error in your template:

```HTML
 <pagination-controls #pagination (pageChange)="currentPage = $event">
```
You should be assigning the `$event` value to the variable `p`, since earlier in the template you have `paginate: { itemsPerPage: 10, currentPage: p }`

Working plunker: http://plnkr.co/edit/dIXCX5tjeSdggGVEgXcf?p=preview
