### ISSUE TITLE
Upgrade to angular rc5

### ISSUE THREAD

**Issue by Yalrafih** [michaelbromley/ng2-pagination#68]
Hi, thanks for contributing!

This project is maintained in my spare time, so in order to help me address your issue as quickly as 
possible, please provide as much of the following information as you can.

-- Michael 

=======

**Angular 2 version**: NA

**ng2-pagination version**: NA

**Description of issue**: Is there any plans to upgrade to angular rc5? if so is there an ETA?

**Steps to reproduce**:NA

**Expected result**:NA

**Actual result**:NA

**Demo**: NA

Any relevant code: NA
```

```

**Comment by icepoint0** [comment]
could it be a  pure:false  PIPE?

**Comment by michaelbromley** [comment]
@Yalrafih Yes, I will upgrade to rc.5, but probably not for another week or two, since the project I use this on is not yet ready to upgrade.

@icepoint0 I don't understand the question. The PaginatePipe is already `pure: false`.

**Comment by michaelbromley** [comment]
Closing in favour of #71
