### ISSUE TITLE
Expression has changed after it was checked

### ISSUE THREAD

**Issue by Miloune** [michaelbromley/ng2-pagination#69]
**Angular 2 version**: RC4

**ng2-pagination version**: 0.3.5

**Description of issue**: 
Get an exception "Expression has changed after it was checked"

**Steps to reproduce**:
http://plnkr.co/edit/9ARgrZ0IDbSQYiJcyKym?p=preview
If you change the page to 2 or more and search an item (like 'item 2'), you will get this error.
(No problem with RC1)

**Expected result**:
No exception

**Actual result**:
Expression has changed after it was checked

**Demo**: http://plnkr.co/edit/9ARgrZ0IDbSQYiJcyKym?p=preview

FYI: https://github.com/angular/angular/issues/11037

**Comment by michaelbromley** [comment]
Thanks for the report. May be related to#48. Will check it out in the next week or so when I get a bit of time.
