### ISSUE TITLE
Update to RC6 

### ISSUE THREAD

**Issue by kgiroux** [michaelbromley/ng2-pagination#71]
Hi, thanks for contributing!

This project is maintained in my spare time, so in order to help me address your issue as quickly as 
possible, please provide as much of the following information as you can.

-- Michael 

=======

**Angular 2 version**:  2.0.0-RC6

**ng2-pagination version**: latest

**Description of issue**:  No compatible with RC6

**Steps to reproduce**: Just run a RC6 Application

**Expected result**: 

**Actual result**:

**Demo**: (if possible, edit [this Plunker demo](http://plnkr.co/edit/JVQMPvV8z2brCIzdG3N4?p=preview) and paste the link to your fork)

Any relevant code:
```
Need to create Module 
```

**Comment by michaelbromley** [comment]
Hi,

Yes, I am hoping to get this done this week. It is dependent on the main app I built this for also migrating to rc.6.

**Comment by michaelbromley** [comment]
Just published 0.4.0 - go and update! :+1:
