### ISSUE TITLE
Weird pagination behaviour after filtering

### ISSUE THREAD

**Issue by hjelperne** [michaelbromley/ng2-pagination#72]
**Angular 2 version**:
2.0.rc5

**ng2-pagination version**:
0.3.5

**Description of issue**:
When filtering, the pagination changes page after an extra input when the current page doesn't have any more elements.

**Steps to reproduce**:
The same happens in the demo at http://michaelbromley.github.io/ng2-pagination/ in the full example.
If you go to page 10 (i.e.) and start writing "sa" in the filtering input, the page goes blank. After deleting the "a", you will be on page 4 with results. It seems that the pagination is changing page "one step too late"

**Expected result**:
At least go to a page with results but, preferably, I believe going to page 1 is the logical page to land on.

**Actual result**:
Empty page on the page you are before starting filtering (if there are not enough results) or some results if the filtering still gives enough results

**Demo**: http://michaelbromley.github.io/ng2-pagination/

**Comment by michaelbromley** [comment]
Thanks for the report. This seems to be due to the fact that the demo component is set to "onPush" change detection. I am working on a new version (rc.6 compatible) which should resolve this issue.

**Comment by michaelbromley** [comment]
Should be fixed now in 0.4.0 (rc.6 update)
