### ISSUE TITLE
Problem when working with AOT

### ISSUE THREAD

**Issue by elvirdolic** [michaelbromley/ng2-pagination#74]
Hi, thanks for contributing!

This project is maintained in my spare time, so in order to help me address your issue as quickly as 
possible, please provide as much of the following information as you can.

-- Michael 

=======

**Angular 2 version**:
rc.7
**ng2-pagination version**:
latest
**Description of issue**:
Error when using AOT compiler
**Steps to reproduce**:
see above
**Expected result**:

**Actual result**:
Error: Unexpected value 'Ng2PaginationModule' imported by the module 'SparepartM
odule'
**Demo**: (if possible, edit [this Plunker demo](http://plnkr.co/edit/JVQMPvV8z2brCIzdG3N4?p=preview) and paste the link to your fork)

Any relevant code:
```

```

```
import { Ng2PaginationModule } from 'ng2-pagination';
  imports: [
    SharedModule,
    PalipediaDocumentModule,
    Ng2PaginationModule,

ngc -p src
```

**Comment by michaelbromley** [comment]
Thanks for the report. I've not done anything with AoT mode yet.

Is the compiler-cli anywhere near stable yet? npm lists it at version 0.6.1 right now - not sure how that relates to the current rc.7 of the core modules. 

I've not seen any docs on doing AoT yet, so I'm not aware if there is anything I need to do differently in order for this lib to work in that mode.

Anyone with useful info is welcome to post it here. Otherwise, it'll probably be at least a few weeks until I even try my main project (for which I develop this lib) in AoT mode...

**Comment by noemi-salaun** [comment]
You need to add metadata.json files for AOT to understand how your lib works.

*.metadata.json are generated by `ngc`, the Angular compiler.

See [AOT documentation](https://angular.io/docs/ts/latest/cookbook/aot-compiler.html)

**Comment by noemi-salaun** [comment]
It looks like AOT doesn't allow template to access private properties of the component. With some tweak on your lib compilation, AOT does not say `Unexpected value 'Ng2PaginationModule' imported by the module ...` anymore, but it says `Property 'hasTemplate' is private and only accessible within class 'PaginationControlsCmp'`

**Comment by michaelbromley** [comment]
@noemi-salaun Thanks, that's really useful. I'll see if I can incorporate those changes when I update to 2.0.0.

**Comment by noemi-salaun** [comment]
I just spend the day updating our internal projects for AOT compatibility. I should be able to do the same with your project. I also make the compability with RollupJS but it looks like you are using webpack to bundle your lib. I have never used webpack 😢 

For ease of the integration of AOT and rollup, and avoid the need to set up projects that will use your lib, it must respect some convention. But I do not want to impose my way of doing to your code 😉

**Comment by Charkhan** [comment]
Ran into the same issue when trying to use AoT on my project.

```
Error: Unexpected value 'Ng2PaginationModule' imported by the module ...
```

Any ETA on a possible fix ? :)

**Comment by noemi-salaun** [comment]
`Unexpected value...` is AoT saying that it cannot find the corresponding metadata.json file.

You can fix it by cloning ng2-pagination and compile it with ngc, to generate this metadata files. Then you can use `npm pack` to generate an archive and `npm install <generated/ng2-pagination.t.gz>` it in your project.

But it's just a temporary fix...

**Comment by Charkhan** [comment]
Tried this way bun ran into another issue :

```
Error: can't find symbol Host exported from module .../metadata.d.ts
```

Not sure about what file to include in the tsconfig.json...

**Comment by HristoKolev** [comment]
The only way I got this to work was by pulling the source. It sounds bad, but just her me.

There are 5 files in this library that are functional(in ~/src/): 

* ng2-pagination.ts
* paginate-pipe.ts
* pagination-controls-cmp.ts
* pagination-service.ts
* template.ts

If you are using ES6 there are 2 (~/dist/):

* ng2-pagination-bundle.js
* ng2-pagination.d.ts

Just put them in a folder and import the module from `ng2-pagination.ts` or `ng2-pagination-bundle.js`.

If you are using TypeScript you are going to get 1 or  2 errors that have to do with private properties that you have to make public or parameters to functions that you have to add.

In the end I got it working perfectly.

Now I just have to wait for @michaelbromley to do his thing.

**Comment by michaelbromley** [comment]
@HristoKolev thanks for the detailed description there. I'll get around to this next week probably.

**Comment by michaelbromley** [comment]
Please see the latest release, 0.5.0, which now includes the `*.metadata.json` files and also should fix the issue with the private field in the template.

I have not had time to try it in an AOT setting, so I cannot guarantee that it is now bug-free. Feedback is most welcome from those already using AOT.

**Comment by HristoKolev** [comment]
Hello again.

While the ngc doesn't complain anymore, the compiled code calls `PaginationControlsCmp.ngOnChanges` with an argument and your code does not provide such argument. When you try to transpile it to JS in my case with Webpack the TypeScript transpiler complains about the `ngOnChanges` signature not including such argument.

Can you please add an argument of type `any` to that method? That will fix the issue.

Thank you for supporting this package, it saved me a lot of time.

**Comment by bnormoyle** [comment]
I'm running into the same issue as @HristoKolev. I can try to get a pull request ready if that would be more convenient.

**Comment by bnormoyle** [comment]
Created pull request #80 to resolve this. Tested with my AOT setup and the resulting build works.

**Comment by michaelbromley** [comment]
The fix from @bnormoyle is now in the new version, 0.5.1. Go get it from npm! 👍

**Comment by michaelbromley** [comment]
@kamighazi can you tell me the following:

* Angular version
* TypeScript version
* Exact text of the error message

**Comment by noemi-salaun** [comment]
When bundling with rollup after AOT compilation, I get import errors for the `PaginationControlsDirective`.

```
Error at /home/noemi/myproject/aot/app/my.component.ngfactory.ts:39:27: Cannot find module '../node_modules/ng2-pagination/dist/pagination-controls.directive.ngfactory'.
```

When I re-run rollup a second time, it works.

I think maybe it's because you do not export `PaginationControlsDirective`.

In **ng2-pagination.ts**

```ts
import {NgModule} from '@angular/core';
import {CommonModule} from '@angular/common';
import {PaginatePipe} from './paginate.pipe';
import {PaginationService} from './pagination.service';
import {PaginationControlsComponent} from './pagination-controls.component';
import {PaginationControlsDirective} from './pagination-controls.directive';

export {PaginationInstance} from './pagination-instance';
export {PaginationService} from './pagination.service';
export {PaginationControlsComponent} from './pagination-controls.component';
export {PaginationControlsDirective} from './pagination-controls.directive'; // <-- ADD THIS
export {PaginatePipe} from './paginate.pipe';
```

**Comment by michaelbromley** [comment]
@noemi-salaun you are totally correct, I forgot to add that. Will fix and issue new release.

**Comment by finalxcode** [comment]
I'm using AOT with rollup but still getting export errors
Angular version:
2.2.0
TypeScript version:
2.0.10
Exact text of the error message:
'Ng2PaginationModule' is not exported by node_modules\ng2-pagination\index.js (imported by app\app.module.js). For help fixing this error see https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
Error: 'Ng2PaginationModule' is not exported by node_modules\ng2-pagination\index.js (imported by app\app.module.js). For help fixing this error see https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module

**Comment by Andrey-Pavlov** [comment]
Have the issue - Error: Unexpected value 'Ng2PaginationModule' imported by the module 
    "ng2-pagination": "1.0.1",
    "@angular/compiler": "2.3.0",

**Comment by JeffLott** [comment]
I was having the same problem, but I was able to solve it by updating the commonJS plugin in my rollup config to have the following namedExport:
'node_modules/ng2-pagination/index.js': ['Ng2PaginationModule']

That fixed the issue for me.
