### ISSUE TITLE
"stringFilter" pipe not working in the pagination using advanced id

### ISSUE THREAD

**Issue by plachy-jozef** [michaelbromley/ng2-pagination#77]
Hi, thanks for contributing!

This project is maintained in my spare time, so in order to help me address your issue as quickly as 
possible, please provide as much of the following information as you can.

-- Michael 

=======

**Angular 2 version**:
2.0.0
**ng2-pagination version**:
0.4.1
**Description of issue**:
Hi Michael.
Thanks for great module.
I'm trying to implement it in my project. Wanted to use the advanced version from your showcase:
http://michaelbromley.github.io/ng2-pagination/
When I copied the code and adjust it to my code the angular is screeming on me this:

> Unhandled Promise rejection:
> 
> Template parse errors:
> Parser Error: Unexpected token | at column 47 in [ngFor let item of collection |  stringFilter: | paginate: config] in AppComponent@76:16 ("
> 
>         <tbody>
>             <tr [ERROR ->]*ngFor="let item of collection |  stringFilter: | paginate: config"> 
>                 <td>{{item.tra"): AppComponent@76:16
> The pipe 'stringFilter' could not be found ("

When I have checked your project repo on gitHub and checked the "paginate-pipe.ts" file I didn't found there the stringFilter pipe. Haven't you included in the 0.4.1 version please or am I missing something?
Thank you very much for your insight, much appreciate it.

**Comment by michaelbromley** [comment]
Hi,

The `stringFilter` in the demo is not a part of this module - it is just something used in the demo app. You can see the source code for it here: https://github.com/michaelbromley/ng2-pagination/blob/47ffe79171b275b41c43fadf3902d956bd491a2f/demo/src/string-filter-pipe.ts

Secondly, your syntax is wrong - the colon is supposed to be followed by a string to filter by: `stringFilter: someString`
