### ISSUE TITLE
Dart port

### ISSUE THREAD

**Issue by laagland** [michaelbromley/ng2-pagination#8]
Hi,

I really like your library but because I'm using Dart with Angular2 instead of typescript I went ahead and made a port to Dart. Please see [https://github.com/laagland/ng2-dart-pagination](https://github.com/laagland/ng2-dart-pagination) for the code. It is almost production ready, just a couple of bugs to squash.

Best,
Louis

**Comment by michaelbromley** [comment]
Excellent! I've added a note to the readme.
