### ISSUE TITLE
Multiple paginations in one page are not reflecting each other

### ISSUE THREAD

**Issue by theunreal** [michaelbromley/ng2-pagination#83]
**Angular 2 version**

2.0.0

**ng2-pagination version**:
0.5.2

**Description of issue**:
When having 2 or more paginations in one page, the pagination controls are not working correctly. Changing one pagination reflect the other. When changing the `(pageChange)="p = $event"` to `(pageChange)="d = $event"` it also linked.

**Steps to reproduce**:
Having 2 or more paginations in one page (Component)

**Expected result**:
Each pagination controls will be associated to their own pagination data

**Actual result**: Moving between pages in one paginations reflect all other paginations in that component.

Any relevant code:
```
<table>
<tr *ngFor="let tip of normal_tips | paginate: { itemsPerPage: 10, currentPage: p }">
...
</tr>
</table>

<pagination-controls (pageChange)="p = $event"></pagination-controls>


<table>
<tr *ngFor="let tip of vip_tips | paginate: { itemsPerPage: 10, currentPage: d }"
 (click)="selectedTip=tip">
</tr>
</table>

<pagination-controls (pageChange)="d = $event"></pagination-controls>
```

**Comment by michaelbromley** [comment]
You need to set the ids if you are using multiple instances. Checkout the [api docs](https://github.com/michaelbromley/ng2-pagination#api)

```HTML
<table>
<tr *ngFor="let tip of vip_tips | paginate: { itemsPerPage: 10, currentPage: d, id: 'd' }"
 (click)="selectedTip=tip">
</tr>
</table>

<pagination-controls (pageChange)="d = $event" id="d"></pagination-controls>
```

**Comment by temchannat** [comment]
Thank you very much. This is very helpful

**Comment by syamkp1986** [comment]
Thanks, that really worked!!! :)

**Comment by Thirumadhu** [comment]
I am trying to use 5 paginations in the same component but I am unable to do. I am getting this error

  src/app/website/my-vehicle/my-vehicle.component.ts:12:16
        12   templateUrl: './my-vehicle.component.html',
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        Error occurs in the template of component MyVehicleComponent.
    src/app/website/my-vehicle/my-vehicle.component.html:592:60 - error NG5002: Parser Error: Unexpected token } at column 110 in [let data of onlineVehicleList | filter:searchText | paginate: { itemsPerPage: 6, currentPage: a, id='second' }] in /home/szigony/Workspace/Projects/rmc_frontend/src/app/website/my-vehicle/my-vehicle.component.html@155:79
    
    592                             nextLabel="Next" (pageChange)="f = $event" id="fifth"></pagination-controls>
                                                                   ~~~~~~~~~~
    
      src/app/website/my-vehicle/my-vehicle.component.ts:12:16
        12   templateUrl: './my-vehicle.component.html',
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        Error occurs in the template of component MyVehicleComponent.
    src/app/website/my-vehicle/my-vehicle.component.html:592:600m - error NG5002: Parser Error: Missing expected : at column 100 in [let data of onTripVehicleList | filter:searchText | paginate: { itemsPerPage: 6, currentPage: b, id='third' }] in /home/szigony/Workspace/Projects/rmc_frontend/src/app/website/my-vehicle/my-vehicle.component.html@281:79
    
    592                             nextLabel="Next" (pageChange)="f = $event" id="fifth"></pagination-controls>
                                                                   ~~~~~~~~~~
    
      src/app/website/my-vehicle/my-vehicle.component.ts:12:16
        12   templateUrl: './my-vehicle.component.html',
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        Error occurs in the template of component MyVehicleComponent.
    src/app/website/my-vehicle/my-vehicle.component.html:592:60 - error NG5002: Parser Error: Unexpected token } at column 109 in [let data of onTripVehicleList | filter:searchText | paginate: { itemsPerPage: 6, currentPage: b, id='third' }] in /home/szigony/Workspace/Projects/rmc_frontend/src/app/website/my-vehicle/my-vehicle.component.html@281:79
    
    592                             nextLabel="Next" (pageChange)="f = $event" id="fifth"></pagination-controls>
                                                                   ~~~~~~~~~~
    
      src/app/website/my-vehicle/my-vehicle.component.ts:12:16
        12   templateUrl: './my-vehicle.component.html',
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        Error occurs in the template of component MyVehicleComponent.
    src/app/website/my-vehicle/my-vehicle.component.html:592:60 - error NG5002: Parser Error: Missing expected : at column 102 in [let data of scheduleVehicleList | filter:searchText | paginate: { itemsPerPage: 6, currentPage: c, id='fourth' }] in /home/szigony/Workspace/Projects/rmc_frontend/src/app/website/my-vehicle/my-vehicle.component.html@407:79
    
    592                             nextLabel="Next" (pageChange)="f = $event" id="fifth"></pagination-controls>
                                                                   ~~~~~~~~~~
    
      src/app/website/my-vehicle/my-vehicle.component.ts:12:16
        12   templateUrl: './my-vehicle.component.html',
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        Error occurs in the template of component MyVehicleComponent.
    src/app/website/my-vehicle/my-vehicle.component.html:592:60 - error NG5002: Parser Error: Unexpected token } at column 112 in [let data of scheduleVehicleList | filter:searchText | paginate: { itemsPerPage: 6, currentPage: c, id='fourth' }] in /home/szigony/Workspace/Projects/rmc_frontend/src/app/website/my-vehicle/my-vehicle.component.html@407:79
    
    592                             nextLabel="Next" (pageChange)="f = $event" id="fifth"></pagination-controls>
                                                                   ~~~~~~~~~~
    
      src/app/website/my-vehicle/my-vehicle.component.ts:12:16
        12   templateUrl: './my-vehicle.component.html',
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        Error occurs in the template of component MyVehicleComponent.
    src/app/website/my-vehicle/my-vehicle.component.html:592:60 - error NG5002: Parser Error: Missing expected : at column 103 in [let data of cancelledVehicleList | filter:searchText | paginate: { itemsPerPage: 6, currentPage: f, id='fifth' }] in /home/szigony/Workspace/Projects/rmc_frontend/src/app/website/my-vehicle/my-vehicle.component.html@532:79
    
    592                             nextLabel="Next" (pageChange)="f = $event" id="fifth"></pagination-controls>
                                                                   ~~~~~~~~~~
    
      src/app/website/my-vehicle/my-vehicle.component.ts:12:16
        12   templateUrl: './my-vehicle.component.html',
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        Error occurs in the template of component MyVehicleComponent.
    src/app/website/my-vehicle/my-vehicle.component.html:592:60 - error NG5002: Parser Error: Unexpected token } at column 112 in [let data of cancelledVehicleList | filter:searchText | paginate: { itemsPerPage: 6, currentPage: f, id='fifth' }] in /home/szigony/Workspace/Projects/rmc_frontend/src/app/website/my-vehicle/my-vehicle.component.html@532:79
    
    592                             nextLabel="Next" (pageChange)="f = $event" id="fifth"></pagination-controls>
                                                                   ~~~~~~~~~~
    
      src/app/website/my-vehicle/my-vehicle.component.ts:12:16
        12   templateUrl: './my-vehicle.component.html',
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        Error occurs in the template of component MyVehicleComponent.
        
        Please help me

**Comment by ousmane0682** [comment]
Hello everyone my pagination is not working. I don't not know what is wrong someone can help me please.

**student.component.html**

<h1>Students</h1>
<div class="dropdown position-absolute top-10 start-50 translate-middle-x">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown"
    aria-expanded="false">
    number
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
    <li><a class="dropdown-item" (click)="changeNumb(5)">5</a></li>
    <li><a class="dropdown-item" (click)="changeNumb(25)">25</a></li>
    <li><a class="dropdown-item" (click)="changeNumb(50)">50</a></li>
    <li><a class="dropdown-item" (click)="changeNumb(75)">75</a></li>
    <li><a class="dropdown-item" (click)="changeNumb(100)">100</a></li>
  </ul>
</div>
<div class="mb-2">
  <button class="btn btn-primary" routerLink="/add">Add New Student</button>
  <div class="col-md-2 float-end row">
    <input type="text" id="name" placeholder="Recherche..." [(ngModel)]="searchText" />
  </div>
</div>
<div>
  <table class="table table-striped">
    <thead>
      <th>ID</th>
      <th>Name</th>
      <th>Email</th>
      <th>Number</th>
    </thead>
    <tbody>
      <tr *ngFor="let student of users|
      paginate: {
        itemsPerPage: 10,
        currentPage: p,
        totalItems: totalLength }
        | searchFilter: searchText " (click)="selectedTip=student">
        <td>{{student.id}}</td>
        <td>{{student.name}}</td>
        <td>{{student.email}}</td>
        <td>{{student.number}}</td>
        <td><button class="btn btn-info" routerLink="/edit/{{student.id}}">Edit</button>&nbsp;<button
            class="btn btn-danger" (click)="deleteStudent(student.id)">Delete</button>
        </td>
      </tr>
    </tbody>
  </table>

  <pagination-controls (pageChange)="p = ($event)" id="id "></pagination-controls>
</div>


**student.component.ts**

import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { StudentService } from '../services/student.service';
import { HttpClient } from '@angular/common/http';
import { ActivatedRoute } from '@angular/router';

@Component({
  selector: 'app-students',
  templateUrl: './students.component.html',
  styleUrls: ['./students.component.scss']
})
export class StudentsComponent implements OnInit {

  totalLength: any;

  users: any[] = [];
  page: any = 10;
  searchText!: string;
  p: number = 1;


  constructor(private studentService: StudentService, private router: Router, private http: HttpClient,
    private route: ActivatedRoute) { }
  user: any = [];
  ngOnInit(): void {
    this.showStudents();
  }

  showStudents() {
    this.studentService.listStudents(this.page).subscribe(student => {
      this.users = student.students.data;

      this.totalLength = this.users.length;

    })
  }
  changeNumb(nbr: any) {
    this.studentService.listStudents(nbr).subscribe(student => {
      this.users = student.students.data;

    })
  }

  deleteStudent(id: any) {
    this.studentService.deleteStudent(id).subscribe(
      res => {
        this.showStudents();
      }
    );


  }


}
