### ISSUE TITLE
the pager is too micro in size how can i increase its size.

### ISSUE THREAD

**Issue by AyzPat** [michaelbromley/ng2-pagination#85]
Hi, thanks for contributing!

I am unable to override my styles on the pagination. SO how do I override???
**ng2-pagination version**:

**Description of issue**:

**Steps to reproduce**:

**Expected result**:

**Actual result**:

**Demo**: (if possible, edit [this Plunker demo](http://plnkr.co/edit/JVQMPvV8z2brCIzdG3N4?p=preview) and paste the link to your fork)

Any relevant code:
```

```

**Comment by michaelbromley** [comment]
Maybe you are having difficulty due to the emulated shadow DOM used by Angular. Try using the `/deep/` selector in your styles to target the default template styles.
