### ISSUE TITLE
how can I paginate the ng2 page using bootstrap only?

### ISSUE THREAD

**Issue by AyzPat** [michaelbromley/ng2-pagination#87]
how can I paginate the ng2 page using bootstrap only? your code works perfectly using the module but my requirement is onmy using bootstrap..

**Comment by HristoKolev** [comment]
I don't think this is the right place to ask this question. Maybe the bootstrap repo? https://github.com/twbs/bootstrap/issues

**Comment by michaelbromley** [comment]
You can create a custom template based on the bootstrap markup: https://github.com/michaelbromley/ng2-pagination#custom-templates

What I have done in one of my projects which uses this, is to wrap the PaginationControlsCmp in a custom component which has a custom template and passes through the same API Inputs & Outputs to the inner controls component.
