### ISSUE TITLE
What should be the default prefix to Angular 2 packages?

### ISSUE THREAD

**Issue by Urigo** [michaelbromley/ng2-pagination#9]
Hi friend!
Question, what should be the default prefix for Angular 2 packages?

in Angular 1.x it was `angular-`, like `angular-google-maps` `angular-ui-router` etc..
I saw that for maps they registered as `angular2-google-maps` - https://angular-maps.com/

Should that be the standard or maybe `ng2-` ?

**Comment by michaelbromley** [comment]
Hey there!

Good question. Personally I chose ng2 mainly for the fact that it is short and conveys the same idea as "angular2". 

A couple of examples of "ng2" in the wild - 
* [ng2-translate](https://github.com/ocombe/ng2-translate) by @ocombe (68 stars, 10 forks)
* [ng2-bootstrap](https://github.com/valor-software/ng2-bootstrap) (304 stars, 54 forks) - they even renamed it from "angular2-bootstrap"

I don't feel strongly either way, but I imagine that one or the other will emerge as the generally-preferred prefix for the popular modules.

**Comment by ocombe** [comment]
if your lib is strictly for Angular 2, use "angular2-" or "ng2-" (I prefer this one because it's shorter).
If you think that your lib could be used for something else as well (because it doesn't use anything from angular 2, or because the "angular" part could be moved to a plugin later), then don't use "angular2" or "ng2" in the name.

**Comment by Urigo** [comment]
is there someone we should ask from the Angular team maybe? 
I know it's not important at all, but it was nice back in Angular 1.x that they decided on a convention as some point and it was nicer.
Also, I would prefer `angular2-` because it means that the imports will be more consistent as we already have to do - 
`import something from "angular2/core/something"`
`import that from "angular2-pagination/that"`

**Comment by ocombe** [comment]
We talked about it with @NathanWalker somewhere, not sure where, maybe in the angular cli repo?

**Comment by michaelbromley** [comment]
Gonna close this now, but for the record I have seen a ton of modules come out recently with the "ng2-" prefix, so I feel that this is probably going to become the de-facto standard.
