### ISSUE TITLE
The pipe 'paginate' could not be found

### ISSUE THREAD

**Issue by nadeemse** [michaelbromley/ng2-pagination#90]
Error: Template parse errors:
The pipe 'paginate' could not be found ("
                </div>

```
            <barrat-product-view [ERROR ->]*ngFor="let item of items | paginate: {  id: 'server', itemsPerPage: pagination?.perPageItems, curren"): ProductsComponent@26:25
```

'pagination-controls' is not a known element:
1. If 'pagination-controls' is an Angular component, then verify that it is part of this module.
2. If 'pagination-controls' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("/barrat-product-view>
            <div class="spinner" [ngClass]="{ 'hidden': !loading }"></div>
                [ERROR ->]<pagination-controls (pageChange)="getPage($event)" id="server"></pagination-controls>

**Comment by michaelbromley** [comment]
Sound like you may not have correctly imported the ng2PaginationModule into your app. Can you show you app module definition?

**Comment by Sevensnake** [comment]
Having the same problem. ` <pagination [totalItems]="bigTotalItems" [(ngModel)]="page"  [id]="config.id"   [directionLinks]="directionLinks" [maxSize]="maxSize" class="pagination-sm"  (pageChange)="onPageChange($event)"
                        [boundaryLinks]="true"></pagination>
In my app.module.ts
import { PaginationModule  } from 'ng2-bootstrap/components/pagination';
 imports:PaginationModule `
I see the Pagination tool but as soon as I add a pipe  and the name I get the same msg

**Comment by krojew** [comment]
Same problem here - module correctly imported, but no pipe.

**Comment by michaelbromley** [comment]
@Sevensnake you are importing from `'ng2-bootstrap/components/pagination'` - that is a completely different module, unrelated to this one.

@krojew Let me know the version of ng2-pagination and the version of Angular you are using.

**Comment by krojew** [comment]
Angular: 2.1.0
ng2-pagination: 0.5.1

**Comment by michaelbromley** [comment]
@krojew thanks, and can you show me how you are declaring your app module which uses ng2-paginate? And also your template code where you use the pipe?

**Comment by krojew** [comment]
I tried importing it in two ways, both do not work:

First: CoreModule importing all dependencies, which is imported by AppModule (truncated for readability):

```
import { NgModule, Optional, SkipSelf } from '@angular/core';
import { Ng2PaginationModule } from 'ng2-pagination';

import { throwIfAlreadyLoaded } from './module-import-guard';

@NgModule({
    exports: [
        Ng2PaginationModule,
    ],
    imports: [
        Ng2PaginationModule,
    ],
})
export class CoreModule {
    public constructor(@Optional() @SkipSelf() parentModule: CoreModule) {
        throwIfAlreadyLoaded(parentModule, 'CoreModule');
    }
}
```
```
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { BrowserModule } from '@angular/platform-browser';

import { AppRoutingModule } from './app-routing.module';
import { CoreModule } from './core/core.module';

import { AppComponent } from './app.component';
import { UserListComponent } from './user-list/user-list.component';

@NgModule({
    bootstrap: [
        AppComponent
    ],
    declarations: [
        AppComponent,
        UserListComponent,
    ],
    imports: [
        AppRoutingModule,
        BrowserModule,
        CommonModule,
        CoreModule,
        FormsModule,
        HttpModule
    ],
})
export class AppModule {
}
```

Second: imported directly by AppModule:

```
import { CommonModule } from '@angular/common';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
import { BrowserModule } from '@angular/platform-browser';
import { Ng2PaginationModule } from 'ng2-pagination';

import { AppRoutingModule } from './app-routing.module';
import { CoreModule } from './core/core.module';

import { AppComponent } from './app.component';
import { UserListComponent } from './user-list/user-list.component';

@NgModule({
    bootstrap: [
        AppComponent
    ],
    declarations: [
        AppComponent,
        UserListComponent,
    ],
    imports: [
        AppRoutingModule,
        BrowserModule,
        CommonModule,
        CoreModule,
        FormsModule,
        HttpModule,
        Ng2PaginationModule
    ],
})
export class AppModule {
}
```

And the usage in the template:

```
<tr *ngFor="let user of users | async | pagiante: { itemsPerPage: 50, currentPage: p }">
</tr>
```

**Comment by michaelbromley** [comment]
Not sure if this is also in your code, but in the template snippet, you have a typo: "pagiante" rather than "paginate".

**Comment by krojew** [comment]
Wow, can't believe I didn't notice it. Thanks, everything works fine.

**Comment by michaelbromley** [comment]
@krojew no worries. Sometimes takes another pair of eyes to spot the obvious ;)

**Comment by Sevensnake** [comment]
Thanks problem resolved.  to answer @Sevensnake you are importing from 'ng2-bootstrap/components/pagination' - that is a completely different module, unrelated to this one.
wrong pagth

**Comment by kenadet** [comment]
I got this error: ```node_modules/ngx-pagination/dist/pagination.service.d.ts (1,30): Cannot find module '@angular/core'.```. Can we make this work with Angular 4?

**Comment by nishant0131** [comment]
I got this error: node_modules/ngx-pagination/dist/pagination.service.d.ts (1,30): Cannot find module '@angular/core'.. Can we make this work with Angular 4?
Got the same error in Angular 4
