### ISSUE TITLE
Pagination controls with custom template break when placed before pipe usage

### ISSUE THREAD

**Issue by goodsign** [michaelbromley/ng2-pagination#91]
Hey @michaelbromley 
# 

**Angular 2 version**: ~2.0.0

**ng2-pagination version**: 0.5.1

**Description of issue**:

If I use custom template and put `<pagination-controls>` **before** the element where the corresponding `paginate` pipe was used, the pagination control starts to behave weird: if I click on `...`, the selection and position of `...` gets messed up. However, if I have exactly the same setup, but put the `<pagination-controls>` item **after** the pipe or don't use custom template, everything is fine.

**Steps to reproduce**:
1. Prepare data to show 10 pages
2. Use custom template from [the example](https://github.com/michaelbromley/ng2-pagination#custom-templates).
3. Put the `<pagination-controls>` before the element which uses the `pagination` pipe.
4. Click on '...'

**Expected result**:

After click on `...` controls should look like

`1` `...` `5` `_6_` `7` `...` `10`

**Actual result**:

After click on `...` controls look like

`1` `2` `3` `4` `5` `_..._` `10`

**Demo**: http://plnkr.co/edit/lxcR691zFSVcKAjnzCxf?p=preview

Note: If you use exactly the same plunkr but just move the `pagination-controls` below the `ul`, the bug disappears.

**Comment by michaelbromley** [comment]
Hi,

Thanks for the report. I have come to think that there are fundamental problems with the implementation of custom templates, and I plan on a breaking refactor soon, which will address this issue and others. See https://github.com/michaelbromley/ng2-pagination/issues/88#issuecomment-255966468

Can't say exactly when this will land, but possible within the next couple of weeks.

**Comment by michaelbromley** [comment]
Fixed in v1.0.0. Note breaking changes with how custom templates work now.
