### ISSUE TITLE
Compilation iisue

### ISSUE THREAD

**Issue by surjitkumar25** [michaelbromley/ng2-pagination#93]
Hi, thanks for contributing!

This project is maintained in my spare time, so in order to help me address your issue as quickly as 
possible, please provide as much of the following information as you can.

-- Michael 

=======

**Angular 2 version**:

**ng2-pagination version**:

**Description of issue**:

**Steps to reproduce**:

**Expected result**:

**Actual result**:

**Demo**: (if possible, edit [this Plunker demo](http://plnkr.co/edit/JVQMPvV8z2brCIzdG3N4?p=preview) and paste the link to your fork)

Any relevant code:
```
http://prntscr.com/d20io1
```

**Comment by michaelbromley** [comment]
Hi,

I'm sorry, this is an incomplete issue. There is no description other than a screenshot with no context. I'm closing this now, but if you are able to add more context (i.e. actually fill out the prompts in the issue template), I can take another look.

**Comment by surjitkumar25** [comment]
Hi,

I just import the ng2-pagination in my module and compiled it and it returned that syntax error

**Comment by michaelbromley** [comment]
Sounds like you might have run into an issue with TypeScript version support. See https://github.com/michaelbromley/ng2-pagination/issues/81

Basically there is an error if you are not yet using TypeScript 2.0+, but I am actually working on fixing that right now.
