### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by Sevensnake** [michaelbromley/ng2-pagination#97]
Is there a way to over ride the CSS or change the classes names. Does not seem to let you do that.

**Comment by michaelbromley** [comment]
Yes, you can override the styles by using the `/deep/` selector to apply your styles within the emulated shadow DOM. See https://github.com/michaelbromley/ng2-pagination/issues/64

To change the class names you will need to implement a custom template, see here: https://github.com/michaelbromley/ng2-pagination#paginationcontrolsdirective
