### ISSUE TITLE
Problem with the pagination visual size. 

### ISSUE THREAD

**Issue by virgil-av** [michaelbromley/ng2-pagination#98]
**Angular 2 version**:
2.1.0

**ng2-pagination version**:
latest

https://s17.postimg.org/9d7zek7dr/paginator.png

Is there a way to make it bigger ?  

// edit:  for some reason it inherits the bootstrap html font-size of 10px

**Comment by AyzPat** [comment]
check it in the ng2-pagination folder under node-modules and find the template.js file. in that locate font-size='some' rem.. increase it .. u ll get what u require..

**Comment by michaelbromley** [comment]
See https://github.com/michaelbromley/ng2-pagination/issues/64
