### ISSUE TITLE
Display Total Items on the table beside the pagination

### ISSUE THREAD

**Issue by vijender1256** [michaelbromley/ng2-pagination#99]
I am trying to display like 1 - 20 of 65 items beside the pagination, how would I do that ?, like number of items and page number after i click on paginate.

http://plnkr.co/edit/JVQMPvV8z2brCIzdG3N4?p=preview

**Comment by michaelbromley** [comment]
> how would I do that ?

Do you mean "what is the calculation I must do to derive these values?", or "how to I display the values in a custom template?"

**Comment by vijender1256** [comment]
@michaelbromley Thanks, how to display values on the template ?

**Comment by michaelbromley** [comment]
Okay, well there is nothing special to this - just basic Angular templates and some simple calculations:

```HTML
 Displaying {{ (p - 1) * itemsPerPage + 1 }} - {{ p * itemsPerPage }} of {{ collection.length }}
```

**Comment by Delasal** [comment]
How to get total item in pagination after applied custom pipe

**Comment by michaelbromley** [comment]
@Delasal See https://github.com/michaelbromley/ngx-pagination/issues/166
